## CIA World Fact Book: Basic Cleaning & Inspection

In [1]:
import pandas as pd
import numpy as np

#### Load Data
258 countries<br>
980 columns

In [8]:
wfb_df = pd.read_csv('/Users/placiermoise/Documents/BHTDataVisualizationCourse/data/countries.csv')
wfb_df.head()

,Country,url,Introduction: Background,Geography: Location,Geography: Geographic coordinates,Geography: Map references,Geography: Area - total,Geography: Area - land,Geography: Area - water,Geography: Area - comparative,...,Transportation: Waterways - note 1,Transportation: Waterways - note 2,Transportation: Waterways - top ten largest natural lakes (by surface area),Transportation: Waterways - note 3,Space: Space launch site(s) - note,Transnational Issues: Refugees and internally displaced persons,Transnational Issues: Trafficking in persons - Tier 2 Watch List,Transnational Issues: Trafficking in persons - Tier 3,Transnational Issues: Illicit drugs - cocaine,Transnational Issues: Illicit drugs - opiates
0,Afghanistan,https://www.cia.gov/the-world-factbook/countri...,Ahmad Shah DURRANI unified the Pashtun tribes ...,"Southern Asia, north and west of Pakistan, eas...","33 00 N, 65 00 E",Asia,"652,230 sq km","652,230 sq km",0 sq km,almost six times the size of Virginia; slightl...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Akrotiri,https://www.cia.gov/the-world-factbook/countri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,https://www.cia.gov/the-world-factbook/countri...,After declaring independence from the Ottoman ...,"Southeastern Europe, bordering the Adriatic Se...","41 00 N, 20 00 E",Europe,"28,748 sq km","27,398 sq km","1,350 sq km",slightly smaller than Maryland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Algeria,https://www.cia.gov/the-world-factbook/countri...,"Algeria has known many empires and dynasties, ...","Northern Africa, bordering the Mediterranean S...","28 00 N, 3 00 E",Africa,"2,381,740 sq km","2,381,740 sq km",0 sq km,slightly less than 3.5 times the size of Texas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,American Samoa,https://www.cia.gov/the-world-factbook/countri...,Tutuila -- the largest island in American Samo...,"Oceania, group of islands in the South Pacific...","14 20 S, 170 00 W",Oceania,224 sq km,224 sq km,0 sq km,"slightly larger than Washington, DC",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
wfb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Columns: 980 entries, Country to Transnational Issues: Illicit drugs - opiates
dtypes: float64(10), object(970)
memory usage: 1.9+ MB

In [10]:
wfb_df.describe()

,Transportation: Ports - large,Transportation: Ports - medium,Transportation: Ports - small,Transportation: Ports - very small,Transportation: Ports - ports with oil terminals,"Geography: Natural hazards - Midway Islands, Johnston, and Palmyra Atolls",Transportation: Ports - size unknown,Geography: Coastline - Ile Saint-Paul (Ile Amsterdam et Ile Saint-Paul),Geography: Coastline - Ascension Island,Geography: Natural hazards - Volcano statistics
count,185.000000,185.000000,185.000000,185.000000,185.000000,0.0,22.000000,0.0,0.0,0.0
mean,0.918919,1.967568,5.497297,11.329730,9.043243,NaN,5.863636,NaN,NaN,NaN
std,2.337994,4.420681,13.963510,38.840454,20.105382,NaN,12.773840,NaN,NaN,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,NaN,NaN,NaN
25%,0.000000,0.000000,0.000000,1.000000,1.000000,NaN,1.000000,NaN,NaN,NaN
50%,0.000000,1.000000,1.000000,3.000000,3.000000,NaN,1.000000,NaN,NaN,NaN
75%,1.000000,2.000000,4.000000,8.000000,8.000000,NaN,4.750000,NaN,NaN,NaN
max,21.000000,38.000000,132.000000,475.000000,204.000000,NaN,59.000000,NaN,NaN,NaN

In [11]:
#see all countries
print(wfb_df['Country'].values)

['Afghanistan' 'Akrotiri' 'Albania' 'Algeria' 'American Samoa' 'Andorra'
 'Angola' 'Anguilla' 'Antarctica' 'Antigua and Barbuda' 'Argentina'
 'Armenia' 'Aruba' 'Ashmore and Cartier Islands' 'Australia' 'Austria'
 'Azerbaijan' 'Bahamas, The' 'Bahrain' 'Baker Island' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan'
 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Bouvet Island' 'Brazil'
 'British Indian Ocean Territory' 'British Virgin Islands' 'Brunei'
 'Bulgaria' 'Burkina Faso' 'Burma' 'Burundi' 'Cabo Verde' 'Cambodia'
 'Cameroon' 'Canada' 'Cayman Islands' 'Central African Republic' 'Chad'
 'Chile' 'China' 'Christmas Island' 'Clipperton Island'
 'Cocos (Keeling) Islands' 'Colombia' 'Comoros'
 'Congo, Democratic Republic of the' 'Congo, Republic of the'
 'Cook Islands' 'Coral Sea Islands' 'Costa Rica' 'Croatia' 'Cuba'
 'Curacao' 'Cyprus' 'Czechia' 'Denmark' 'Dhekelia' 'Djibouti' 'Dominica'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'Equatorial Guinea'
 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia'
 'Falkland Islands (Islas Malvinas)' 'Faroe Islands' 'Fiji' 'Finland'
 'France' 'French Polynesia' 'French Southern and Antarctic Lands' 'Gabon'
 'Gambia, The' 'Gaza Strip' 'Georgia' 'Germany' 'Ghana' 'Gibraltar'
 'Greece' 'Greenland' 'Grenada' 'Guam' 'Guatemala' 'Guernsey' 'Guinea'
 'Guinea-Bissau' 'Guyana' 'Haiti' 'Heard Island and McDonald Islands'
 'Holy See (Vatican City)' 'Honduras' 'Hong Kong' 'Howland Island'
 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq' 'Ireland'
 'Isle of Man' 'Israel' 'Italy' 'Jamaica' 'Jan Mayen' 'Japan'
 'Jarvis Island' 'Jersey' 'Johnston Atoll' 'Jordan' 'Kazakhstan' 'Kenya'
 'Kingman Reef' 'Kiribati' 'Korea, North' 'Korea, South' 'Kosovo' 'Kuwait'
 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon' 'Lesotho' 'Liberia' 'Libya'
 'Liechtenstein' 'Lithuania' 'Luxembourg' 'Macau' 'Madagascar' 'Malawi'
 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Marshall Islands' 'Mauritania'
 'Mauritius' 'Mexico' 'Micronesia, Federated States of' 'Midway Islands'
 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Montserrat' 'Morocco'
 'Mozambique' 'Namibia' 'Nauru' 'Navassa Island' 'Nepal' 'Netherlands'
 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'Niue'
 'Norfolk Island' 'North Macedonia' 'Northern Mariana Islands' 'Norway'
 'Oman' 'Pakistan' 'Palau' 'Palmyra Atoll' 'Panama' 'Papua New Guinea'
 'Paracel Islands' 'Paraguay' 'Peru' 'Philippines' 'Pitcairn Islands'
 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Romania' 'Russia' 'Rwanda'
 'Saint Barthelemy' 'Saint Helena, Ascension, and Tristan da Cunha'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Martin'
 'Saint Pierre and Miquelon' 'Saint Vincent and the Grenadines' 'Samoa'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia'
 'Seychelles' 'Sierra Leone' 'Singapore' 'Sint Maarten' 'Slovakia'
 'Slovenia' 'Solomon Islands' 'Somalia' 'South Africa' 'South Sudan'
 'Spain' 'Spratly Islands' 'Sri Lanka' 'Sudan' 'Suriname' 'Svalbard'
 'Sweden' 'Switzerland' 'Syria' 'Taiwan' 'Tajikistan' 'Tanzania'
 'Thailand' 'Timor-Leste' 'Togo' 'Tokelau' 'Tonga' 'Trinidad and Tobago'
 'Tunisia' 'Turkey (Turkiye)' 'Turkmenistan' 'Turks and Caicos Islands'
 'Tuvalu' 'Uganda' 'Ukraine' 'United Arab Emirates' 'United Kingdom'
 'United States' 'Uruguay' 'Uzbekistan' 'Vanuatu' 'Venezuela' 'Vietnam'
 'Virgin Islands' 'Wake Island' 'Wallis and Futuna' 'West Bank' 'World'
 'Yemen' 'Zambia' 'Zimbabwe']

#### Remove non-independent countries; Reset index as 'Country'
After Cleaning:<br>
206 countries

In [12]:
#remove non independent countries
#set 'Country' as the index
non_countries = [
     'Akrotiri','American Samoa' , 'Antarctica', 'Antigua and Barbuda','Ashmore and Cartier Islands',
     'Baker Island', 'Bouvet Island', 'British Indian Ocean Territory', 'British Virgin Islands', 
     'Cayman Islands', 'Christmas Island', 'Clipperton Island', 'Cocos (Keeling) Islands', 'Coral Sea Islands',
     'Dhekelia', 'Falkland Islands (Islas Malvinas)', 'Faroe Islands', 'French Polynesia', 'French Southern and Antarctic Lands',
     'Gibraltar', 'Guernsey' , 'Heard Island and McDonald Islands', 'Howland Island','Isle of Man','Jan Mayen',
     'Jarvis Island', 'Jersey', 'Johnston Atoll','Kingman Reef','Macau' , 'Midway Islands', 'Montserrat','Navassa Island',
     'New Caledonia','Niue', 'Norfolk Island','Northern Mariana Islands', 'Palmyra Atoll', 'Paracel Islands','Pitcairn Islands',
     'Saint Barthelemy', 'Saint Helena, Ascension, and Tristan da Cunha', 'Saint Martin', 'Saint Pierre and Miquelon','Sint Maarten',
     'Spratly Islands', 'Svalbard', 'Tokelau', 'Turks and Caicos Islands', 'Virgin Islands' ,'Wake Island', 'Wallis and Futuna'
]

wfb_df.set_index('Country', inplace=True)
wfb_df.drop(non_countries, axis=0, inplace=True)
print(wfb_df.info())
wfb_df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 206 entries, Afghanistan to Zimbabwe
Columns: 979 entries, url to Transnational Issues: Illicit drugs - opiates
dtypes: float64(10), object(969)
memory usage: 1.5+ MB
None

,url,Introduction: Background,Geography: Location,Geography: Geographic coordinates,Geography: Map references,Geography: Area - total,Geography: Area - land,Geography: Area - water,Geography: Area - comparative,Geography: Land boundaries - total,...,Transportation: Waterways - note 1,Transportation: Waterways - note 2,Transportation: Waterways - top ten largest natural lakes (by surface area),Transportation: Waterways - note 3,Space: Space launch site(s) - note,Transnational Issues: Refugees and internally displaced persons,Transnational Issues: Trafficking in persons - Tier 2 Watch List,Transnational Issues: Trafficking in persons - Tier 3,Transnational Issues: Illicit drugs - cocaine,Transnational Issues: Illicit drugs - opiates
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,https://www.cia.gov/the-world-factbook/countri...,Ahmad Shah DURRANI unified the Pashtun tribes ...,"Southern Asia, north and west of Pakistan, eas...","33 00 N, 65 00 E",Asia,"652,230 sq km","652,230 sq km",0 sq km,almost six times the size of Virginia; slightl...,"5,987 km",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Albania,https://www.cia.gov/the-world-factbook/countri...,After declaring independence from the Ottoman ...,"Southeastern Europe, bordering the Adriatic Se...","41 00 N, 20 00 E",Europe,"28,748 sq km","27,398 sq km","1,350 sq km",slightly smaller than Maryland,691 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Algeria,https://www.cia.gov/the-world-factbook/countri...,"Algeria has known many empires and dynasties, ...","Northern Africa, bordering the Mediterranean S...","28 00 N, 3 00 E",Africa,"2,381,740 sq km","2,381,740 sq km",0 sq km,slightly less than 3.5 times the size of Texas,"6,734 km",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andorra,https://www.cia.gov/the-world-factbook/countri...,The landlocked Principality of Andorra -- one ...,"Southwestern Europe, Pyrenees mountains, on th...","42 30 N, 1 30 E",Europe,468 sq km,468 sq km,0 sq km,"2.5 times the size of Washington, DC",118 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Angola,https://www.cia.gov/the-world-factbook/countri...,Bantu-speaking people settled in the area now ...,"Southern Africa, bordering the South Atlantic ...","12 30 S, 18 30 E",Africa,"1,246,700 sq km","1,246,700 sq km",0 sq km,about eight times the size of Georgia; slightl...,"5,369 km",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Change column 'Geography: Geographic coordinates' to Float columns('Geography: Latitude', 'Geography: Longitude')

In [13]:
#make copy for string manipulation
location_df = wfb_df[['Geography: Geographic coordinates']]
#remove comma deperating latitude and longitude coordinates
location_df['Geography: Geographic coordinates'] = location_df['Geography: Geographic coordinates'].str.replace(',','')
#get degree, minutes, and direction
location_df[['lat_degree', 'lat_minutes', 'lat_direction','long_degree', 'long_minutes', 'long_direction']] = location_df['Geography: Geographic coordinates'].str.split(' ',expand=True)

#calculate latitude decimal coordinates
location_df['lat_decimal']= location_df['lat_degree'].astype(float) + location_df['lat_minutes'].astype(float)/60
location_df.loc[location_df['lat_direction'] == 'S', 'lat_decimal'] *= -1
#save to original data fram
wfb_df['Geography: Latitude'] = location_df['lat_decimal']

#repeat calculation for longitude
location_df['long_decimal']= location_df['long_degree'].astype(float) + location_df['long_minutes'].astype(float)/60
negative_indices = location_df[location_df['long_direction'] == 'S']
location_df.loc[location_df['long_direction'] == 'W', 'long_decimal'] *= -1
wfb_df['Geography: Longitude'] = location_df['long_decimal']

wfb_df[['Geography: Latitude', 'Geography: Longitude']]

/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/3602128034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location_df['Geography: Geographic coordinates'] = location_df['Geography: Geographic coordinates'].str.replace(',','')
/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/3602128034.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location_df[['lat_degree', 'lat_minutes', 'lat_direction','long_degree', 'long_minutes', 'long_direction']] = location_df['Geography: Geographic coordinates'].str.split(' ',expand=True)
/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/3602128034.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location_df[['lat_degree', 'lat_minutes', 'lat_direction','long_degree', 'long_minutes', 'long_direction']] = location_df['Geography: Geographic coordinates'].str.split(' ',expand=True)
/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/3602128034.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location_df[['lat_degree', 'lat_minutes', 'lat_direction','long_degree', 'long_minutes', 'long_direction']] = location_df['Geography: Geographic coordinates'].str.split(' ',expand=True)
/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/3602128034.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location_df[['lat_degree', 'lat_minutes', 'lat_direction','long_degree', 'long_minutes', 'long_direction']] = location_df['Geography: Geographic coordinates'].str.split(' ',expand=True)
/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/3602128034.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location_df[['lat_degree', 'lat_minutes', 'lat_direction','long_degree', 'long_minutes', 'long_direction']] = location_df['Geography: Geographic coordinates'].str.split(' ',expand=True)
/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/3602128034.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location_df[['lat_degree', 'lat_minutes', 'lat_direction','long_degree', 'long_minutes', 'long_direction']] = location_df['Geography: Geographic coordinates'].str.split(' ',expand=True)
/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/3602128034.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location_df['lat_decimal']= location_df['lat_degree'].astype(float) + location_df['lat_minutes'].astype(float)/60
/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/3602128034.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location_df['long_decimal']= location_df['long_degree'].astype(float) + location_df['long_minutes'].astype(float)/60

             Geography: Latitude  Geography: Longitude
Country
Afghanistan                 33.0                 65.00
Albania                     41.0                 20.00
Algeria                     28.0                  3.00
Andorra                     42.5                  1.50
Angola                     -12.5                 18.50
...                          ...                   ...
West Bank                   32.0                 35.25
World                        NaN                   NaN
Yemen                       15.0                 48.00
Zambia                     -15.0                 30.00
Zimbabwe                   -20.0                 30.00

[206 rows x 2 columns]

#### View all colum names

In [14]:
# Show all columns (set to None for unlimited)
pd.set_option('display.max_columns', None)

for column in wfb_df:
    print(f'{column}')

url
Introduction: Background
Geography: Location
Geography: Geographic coordinates
Geography: Map references
Geography: Area - total
Geography: Area - land
Geography: Area - water
Geography: Area - comparative
Geography: Land boundaries - total
Geography: Land boundaries - border countries (6)
Geography: Coastline
Geography: Maritime claims
Geography: Climate
Geography: Terrain
Geography: Elevation - highest point
Geography: Elevation - lowest point
Geography: Elevation - mean elevation
Geography: Natural resources
Geography: Land use - agricultural land
Geography: Land use - forest
Geography: Land use - other
Geography: Irrigated land
Geography: Major lakes (area sq km) - salt water lake(s)
Geography: Major rivers (by length in km)
Geography: Major rivers (by length in km) - note
Geography: Major watersheds (area sq km)
Geography: Population distribution
Geography: Natural hazards
Geography: Geography - note
People and Society: Population - total
People and Society: Population - male
People and Society: Population - female
People and Society: Nationality - noun
People and Society: Nationality - adjective
People and Society: Ethnic groups
People and Society: Languages
People and Society: Languages - major-language sample(s)
People and Society: Languages - note 1
People and Society: Languages - note 2
People and Society: Religions
People and Society: Age structure - 0-14 years
People and Society: Age structure - 15-64 years
People and Society: Age structure - 65 years and over
People and Society: Dependency ratios - total dependency ratio
People and Society: Dependency ratios - youth dependency ratio
People and Society: Dependency ratios - elderly dependency ratio
People and Society: Dependency ratios - potential support ratio
People and Society: Median age - total
People and Society: Median age - male
People and Society: Median age - female
People and Society: Population growth rate
People and Society: Birth rate
People and Society: Death rate
People and Society: Net migration rate
People and Society: Population distribution
People and Society: Urbanization - urban population
People and Society: Urbanization - rate of urbanization
People and Society: Major urban areas - population
People and Society: Sex ratio - at birth
People and Society: Sex ratio - 0-14 years
People and Society: Sex ratio - 15-64 years
People and Society: Sex ratio - 65 years and over
People and Society: Sex ratio - total population
People and Society: Mother's mean age at first birth
People and Society: Mother's mean age at first birth - note
People and Society: Maternal mortality ratio
People and Society: Infant mortality rate - total
People and Society: Infant mortality rate - male
People and Society: Infant mortality rate - female
People and Society: Life expectancy at birth - total population
People and Society: Life expectancy at birth - male
People and Society: Life expectancy at birth - female
People and Society: Total fertility rate
People and Society: Gross reproduction rate
People and Society: Contraceptive prevalence rate
People and Society: Contraceptive prevalence rate - note
People and Society: Drinking water source - improved
People and Society: Drinking water source - unimproved
People and Society: Current health expenditure
People and Society: Physician density
People and Society: Hospital bed density
People and Society: Sanitation facility access - improved
People and Society: Sanitation facility access - unimproved
People and Society: Obesity - adult prevalence rate
People and Society: Alcohol consumption per capita - total
People and Society: Alcohol consumption per capita - beer
People and Society: Alcohol consumption per capita - wine
People and Society: Alcohol consumption per capita - spirits
People and Society: Alcohol consumption per capita - other alcohols
People and Society: Tobacco use - total
People and Society: Tobacco use - male
People and Society: Tobacco use - female
People and Society: Children under the age of 5 years underweight
People and Society: Currently married women (ages 15-49)
People and Society: Child marriage - women married by age 15
People and Society: Child marriage - women married by age 18
People and Society: Education expenditures
People and Society: Literacy - definition
People and Society: Literacy - total population
People and Society: Literacy - male
People and Society: Literacy - female
People and Society: School life expectancy (primary to tertiary education) - total
People and Society: School life expectancy (primary to tertiary education) - male
People and Society: School life expectancy (primary to tertiary education) - female
Environment: Environment - current issues
Environment: Environment - international agreements - party to
Environment: Environment - international agreements - signed, but not ratified
Environment: Climate
Environment: Land use - agricultural land
Environment: Land use - forest
Environment: Land use - other
Environment: Urbanization - urban population
Environment: Urbanization - rate of urbanization
Environment: Food insecurity - severe localized food insecurity
Environment: Revenue from forest resources
Environment: Revenue from coal
Environment: Air pollutants - particulate matter emissions
Environment: Air pollutants - carbon dioxide emissions
Environment: Air pollutants - methane emissions
Environment: Waste and recycling - municipal solid waste generated annually
Environment: Major lakes (area sq km) - salt water lake(s)
Environment: Major rivers (by length in km)
Environment: Major rivers (by length in km) - note
Environment: Major watersheds (area sq km)
Environment: Total water withdrawal - municipal
Environment: Total water withdrawal - industrial
Environment: Total water withdrawal - agricultural
Environment: Total renewable water resources
Government: Country name - conventional long form
Government: Country name - conventional short form
Government: Country name - local long form
Government: Country name - local short form
Government: Country name - etymology
Government: Government type
Government: Capital - name
Government: Capital - geographic coordinates
Government: Capital - time difference
Government: Capital - daylight saving time
Government: Capital - etymology
Government: Administrative divisions
Government: Independence
Government: National holiday
Government: Legal system
Government: Constitution - history
Government: International law organization participation
Government: Citizenship - citizenship by birth
Government: Citizenship - citizenship by descent only
Government: Citizenship - dual citizenship recognized
Government: Citizenship - residency requirement for naturalization
Government: Suffrage
Government: Executive branch - chief of state
Government: Executive branch - head of government
Government: Executive branch - cabinet
Government: Executive branch - elections/appointments
Government: Legislative branch - note
Government: Judicial branch - highest court(s)
Government: Judicial branch - subordinate courts
Government: Political parties
Government: International organization participation
Government: Diplomatic representation in the US
Government: Diplomatic representation in the US - Note
Government: Diplomatic representation from the US - embassy
Government: Flag description
Government: Flag description - note 1
Government: Flag description - note 2
Government: National symbol(s)
Government: National anthem - name
Government: National anthem - lyrics/music
Government: National anthem - note
Government: National heritage - total World Heritage Sites
Government: National heritage - selected World Heritage Site locales
Government: National heritage - note
Economy: Economic overview
Economy: Real GDP (purchasing power parity)
Economy: Real GDP growth rate
Economy: Real GDP per capita
Economy: GDP (official exchange rate)
Economy: Inflation rate (consumer prices)
Economy: GDP - composition, by sector of origin - agriculture
Economy: GDP - composition, by sector of origin - industry
Economy: GDP - composition, by sector of origin - services
Economy: GDP - composition, by end use - household consumption
Economy: GDP - composition, by end use - government consumption
Economy: GDP - composition, by end use - investment in fixed capital
Economy: GDP - composition, by end use - investment in inventories
Economy: GDP - composition, by end use - exports of goods and services
Economy: GDP - composition, by end use - imports of goods and services
Economy: GDP - composition, by end use - note
Economy: Agricultural products
Economy: Industries
Economy: Industrial production growth rate
Economy: Labor force
Economy: Unemployment rate
Economy: Youth unemployment rate (ages 15-24) - total
Economy: Youth unemployment rate (ages 15-24) - male
Economy: Youth unemployment rate (ages 15-24) - female
Economy: Population below poverty line
Economy: Remittances
Economy: Budget - revenues
Economy: Budget - expenditures
Economy: Public debt
Economy: Taxes and other revenues
Economy: Current account balance
Economy: Exports
Economy: Exports - partners
Economy: Exports - commodities
Economy: Imports
Economy: Imports - partners
Economy: Imports - commodities
Economy: Reserves of foreign exchange and gold
Economy: Debt - external
Economy: Debt - external - note
Economy: Exchange rates
Economy: Exchange rates - Exchange rates
Energy: Electricity access - electrification - total population
Energy: Electricity access - electrification - urban areas
Energy: Electricity access - electrification - rural areas
Energy: Electricity - installed generating capacity
Energy: Electricity - consumption
Energy: Electricity - imports
Energy: Electricity - transmission/distribution losses
Energy: Electricity generation sources - fossil fuels
Energy: Electricity generation sources - solar
Energy: Electricity generation sources - hydroelectricity
Energy: Coal - production
Energy: Coal - consumption
Energy: Coal - exports
Energy: Coal - imports
Energy: Coal - proven reserves
Energy: Petroleum - refined petroleum consumption
Energy: Natural gas - production
Energy: Natural gas - consumption
Energy: Natural gas - proven reserves
Energy: Carbon dioxide emissions
Energy: Carbon dioxide emissions - from coal and metallurgical coke
Energy: Carbon dioxide emissions - from petroleum and other liquids
Energy: Carbon dioxide emissions - from consumed natural gas
Energy: Energy consumption per capita
Communications: Telephones - fixed lines - total subscriptions
Communications: Telephones - fixed lines - subscriptions per 100 inhabitants
Communications: Telephones - mobile cellular - total subscriptions
Communications: Telephones - mobile cellular - subscriptions per 100 inhabitants
Communications: Telecommunication systems - general assessment
Communications: Telecommunication systems - domestic
Communications: Telecommunication systems - international
Communications: Broadcast media
Communications: Internet country code
Communications: Internet users - percent of population
Communications: Broadband - fixed subscriptions - total
Communications: Broadband - fixed subscriptions - subscriptions per 100 inhabitants
Transportation: National air transport system - number of registered air carriers
Transportation: National air transport system - inventory of registered aircraft operated by air carriers
Transportation: National air transport system - annual passenger traffic on registered air carriers
Transportation: National air transport system - annual freight traffic on registered air carriers
Transportation: Civil aircraft registration country code prefix
Transportation: Airports
Transportation: Heliports
Transportation: Pipelines
Transportation: Roadways - total
Transportation: Roadways - paved
Transportation: Roadways - unpaved
Transportation: Waterways
Military and Security: Military and security forces
Military and Security: Military expenditures
Military and Security: Military and security service personnel strengths
Military and Security: Military equipment inventories and acquisitions
Military and Security: Military service age and obligation
Military and Security: Military service age and obligation - note
Military and Security: Military - note
Terrorism: Terrorist group(s) - Terrorist group(s)
Terrorism: Terrorist group(s) - note 1
Terrorism: Terrorist group(s) - note 2
Transnational Issues: Refugees and internally displaced persons - refugees (country of origin)
Transnational Issues: Refugees and internally displaced persons - IDPs
Transnational Issues: Trafficking in persons - tier rating
Transnational Issues: Illicit drugs
Geography: Land boundaries - border countries
Geography: Maritime claims - territorial sea
Geography: Maritime claims - continental shelf
Geography: Major lakes (area sq km) - fresh water lake(s)
People and Society: Ethnic groups - note
People and Society: Religions - note
People and Society: Child marriage - men married by age 18
Environment: Major lakes (area sq km) - fresh water lake(s)
Government: Country name - former
Government: Constitution - amendments
Government: Executive branch - election results
Government: Legislative branch - legislature name
Government: Legislative branch - legislative structure
Government: Legislative branch - chamber name
Government: Legislative branch - number of seats
Government: Legislative branch - electoral system
Government: Legislative branch - scope of elections
Government: Legislative branch - term in office
Government: Legislative branch - most recent election date
Government: Legislative branch - parties elected and seats per party
Government: Legislative branch - percentage of women in chamber
Government: Legislative branch - expected date of next election
Government: Judicial branch - judge selection and term of office
Government: International organization participation - note
Government: Diplomatic representation in the US - chief of mission
Government: Diplomatic representation in the US - chancery
Government: Diplomatic representation in the US - telephone
Government: Diplomatic representation in the US - FAX
Government: Diplomatic representation in the US - email address and website
Government: Diplomatic representation in the US - consulate(s) general
Government: Diplomatic representation from the US - chief of mission
Government: Diplomatic representation from the US - mailing address
Government: Diplomatic representation from the US - telephone
Government: Diplomatic representation from the US - FAX
Government: Diplomatic representation from the US - email address and website
Economy: Credit ratings - Moody's rating
Economy: Credit ratings - Standard & Poors rating
Economy: Credit ratings - note
Economy: Gini Index coefficient - distribution of family income
Economy: Household income or consumption by percentage share - lowest 10%
Economy: Household income or consumption by percentage share - highest 10%
Energy: Electricity - exports
Energy: Petroleum - total petroleum production
Energy: Petroleum - crude oil estimated reserves
Transportation: Railways - total
Transportation: Merchant marine - total
Transportation: Merchant marine - by type
Transportation: Ports - total ports
Transportation: Ports - large
Transportation: Ports - medium
Transportation: Ports - small
Transportation: Ports - very small
Transportation: Ports - ports with oil terminals
Transportation: Ports - key ports
Military and Security: Military and security forces - note
Terrorism: Terrorist group(s) - note
Transnational Issues: Refugees and internally displaced persons - stateless persons
Transnational Issues: Refugees and internally displaced persons - note
Geography: Maritime claims - contiguous zone
Geography: Maritime claims - exclusive fishing zone
Geography: Major aquifers
People and Society: Demographic profile
Environment: Waste and recycling - municipal solid waste recycled annually
Environment: Waste and recycling - percent of municipal solid waste recycled
Environment: Major aquifers
Government: Legislative branch - lower chamber - chamber name
Government: Legislative branch - lower chamber - number of seats
Government: Legislative branch - lower chamber - electoral system
Government: Legislative branch - lower chamber - scope of elections
Government: Legislative branch - lower chamber - term in office
Government: Legislative branch - lower chamber - most recent election date
Government: Legislative branch - lower chamber - parties elected and seats per party
Government: Legislative branch - lower chamber - percentage of women in chamber
Government: Legislative branch - lower chamber - expected date of next election
Government: Legislative branch - upper chamber - chamber name
Government: Legislative branch - upper chamber - number of seats
Government: Legislative branch - upper chamber - electoral system
Government: Legislative branch - upper chamber - scope of elections
Government: Legislative branch - upper chamber - term in office
Government: Legislative branch - upper chamber - most recent election date
Government: Legislative branch - upper chamber - percentage of women in chamber
Government: Legislative branch - upper chamber - expected date of next election
Government: Political parties - note
Economy: Average household expenditures - on food
Economy: Average household expenditures - on alcohol and tobacco
Economy: Public debt - note
Energy: Natural gas - exports
Space: Space agency/agencies
Space: Space launch site(s)
Space: Space program overview
Space: Space program overview - note
Geography: Area - note
Geography: Maritime claims - exclusive economic zone
Geography: Natural hazards - volcanism
People and Society: Languages - note
Government: Country name - abbreviation
Government: Dependency status
Government: Capital - note
Government: Citizenship
Economy: Real GDP (purchasing power parity) - note
Economy: Exports - note
Economy: Imports - note
Geography: Land boundaries - border countries (2)
Government: Flag description - note
Economy: Credit ratings - Fitch rating
Economy: Industrial production growth rate - note
Economy: Exchange rates - note
Geography: Land boundaries - border countries (4)
Energy: Electricity generation sources - biomass and waste
Transportation: Railways - narrow gauge
Military and Security: Military deployments
Government: National coat of arms
Geography: Land boundaries - note
Geography: Elevation - note
People and Society: Population
People and Society: Population - note
Transportation: Transportation - note
Geography: Land boundaries - border countries (5)
Geography: Geography - note - note 1
Geography: Geography - note - note 2
Government: Administrative divisions - note
Government: Legislative branch - upper chamber - parties elected and seats per party
Energy: Electricity generation sources - nuclear
Energy: Electricity generation sources - wind
Energy: Nuclear energy - Number of operational nuclear reactors
Energy: Nuclear energy - Number of nuclear reactors under construction
Energy: Nuclear energy - Net capacity of operational nuclear reactors
Energy: Nuclear energy - Percent of total electricity production
Energy: Natural gas - imports
Government: Executive branch - note
Government: Legislative branch - note 1
Government: Legislative branch - note 2
Energy: Nuclear energy - Number of nuclear reactors permanently shut down
Transportation: Roadways - urban
Transportation: Roadways - non-urban
Geography: Geographic coordinates - note
Geography: Natural resources - note 1
Geography: Natural resources - note 2
Geography: Natural resources - note 3
Geography: Natural resources - note 4
Geography: Geography - note - note 3
People and Society: Urbanization - note
Environment: Urbanization - note
Government: Capital - time zone note
Government: Dependent areas
Government: Diplomatic representation from the US - consulate(s) general
Government: National anthem - note 1
Government: National anthem - note 2
Transportation: Railways - standard gauge
Transportation: Railways - broad gauge

#### View all column names with the specified topic(including Nan count)
Topics include: Geography, People and Society, Environment, Government, Economy, Communications, Transportation,<br>
Energy, Military and Security, Terrorism, Transnational Issues, and Space.

In [135]:
topic = 'Environment:'
topic_df = wfb_df.filter(like=topic, axis=1)

In [136]:
column_names = list(topic_df.columns)
for column in topic_df.columns:
    na_count = topic_df[column].isna().sum()
    column_type = type(topic_df[column][0])
    example = topic_df[column][0]
    print(f'{column}\tNan: {na_count,column_type}\tExample: {example}')

Environment: Environment - current issues	Nan: (0, <class 'str'>)	Example: limited natural freshwater resources; inadequate supplies of potable water; soil degradation; overgrazing; deforestation (much of the remaining forests are being cut down for fuel and building materials); desertification; air and water pollution in overcrowded urban areas
Environment: Environment - international agreements - party to	Nan: (13, <class 'str'>)	Example: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Climate Change-Paris Agreement, Comprehensive Nuclear Test Ban, Desertification, Endangered Species, Environmental Modification, Hazardous Wastes, Marine Dumping-London Convention, Nuclear Test Ban, Ozone Layer Protection
Environment: Environment - international agreements - signed, but not ratified	Nan: (13, <class 'str'>)	Example: Law of the Sea, Marine Life Conservation
Environment: Climate	Nan: (1, <class 'str'>)	Example: arid to semiarid; cold winters and hot summers
Environment: Land use - agricultural land	Nan: (2, <class 'str'>)	Example: 58.1% (2018 est.)agricultural land: arable land: 11.8% (2018)agricultural land: permanent crops: 0.3% (2018)agricultural land: permanent pasture: 46% (2018)
Environment: Land use - forest	Nan: (5, <class 'str'>)	Example: 1.8% (2018 est.)
Environment: Land use - other	Nan: (3, <class 'str'>)	Example: 40.1% (2018)
Environment: Urbanization - urban population	Nan: (1, <class 'str'>)	Example: 26.9% of total population (2023)
Environment: Urbanization - rate of urbanization	Nan: (1, <class 'str'>)	Example: 3.34% annual rate of change (2020-25 est.)
Environment: Food insecurity - severe localized food insecurity	Nan: (181, <class 'str'>)	Example: due to civil conflict, population displacement, and economic slowdown - between November 2021 and March 2022, during the winter lean season, the food insecurity situation was expected to deteriorate and the number of people in "Crisis" or above was likely to increase to 22.8 million, about 35% more than during the same season in 2020/21; following the developments of August 2021 in the country, the international aid flows, an important element of public spending, were halted; the food security situation and agricultural livelihoods in the country is likely to significantly deteriorate in the coming months due to cumulative and cascading impact of multiple shocks, including weather, conflict, economic crisis and the lingering effects of the COVID‑19 pandemic (2022)
Environment: Revenue from forest resources	Nan: (12, <class 'str'>)	Example: 0.2% of GDP (2018 est.)
Environment: Revenue from coal	Nan: (26, <class 'str'>)	Example: 0.45% of GDP (2018 est.)
Environment: Air pollutants - particulate matter emissions	Nan: (13, <class 'str'>)	Example: 62.49 micrograms per cubic meter (2019 est.)
Environment: Air pollutants - carbon dioxide emissions	Nan: (11, <class 'str'>)	Example: 8.67 megatons (2016 est.)
Environment: Air pollutants - methane emissions	Nan: (13, <class 'str'>)	Example: 90.98 megatons (2020 est.)
Environment: Waste and recycling - municipal solid waste generated annually	Nan: (5, <class 'str'>)	Example: 5,628,525 tons (2016 est.)
Environment: Major lakes (area sq km) - salt water lake(s)	Nan: (170, <class 'str'>)	Example: Ab-e Istadah-ye Muqur (endorheic basin) - 520 sq km
Environment: Major rivers (by length in km)	Nan: (126, <class 'str'>)	Example: Amu Darya (shared with Tajikistan [s], Turkmenistan, and Uzbekistan [m]) - 2,620 km; Helmand river source (shared with Iran) - 1,130 km
Environment: Major rivers (by length in km) - note	Nan: (128, <class 'str'>)	Example: – [s] after country name indicates river source; [m] after country name indicates river mouth
Environment: Major watersheds (area sq km)	Nan: (104, <class 'str'>)	Example: Indian Ocean drainage: Indus (1,081,718 sq km)Internal (endorheic basin) drainage: Amu Darya (534,739 sq km); Tarim Basin (1,152,448 sq km)
Environment: Total water withdrawal - municipal	Nan: (24, <class 'str'>)	Example: 200 million cubic meters (2020 est.)
Environment: Total water withdrawal - industrial	Nan: (27, <class 'str'>)	Example: 170 million cubic meters (2020 est.)
Environment: Total water withdrawal - agricultural	Nan: (27, <class 'str'>)	Example: 20 billion cubic meters (2020 est.)
Environment: Total renewable water resources	Nan: (11, <class 'str'>)	Example: 65.33 billion cubic meters (2020 est.)
Environment: Major lakes (area sq km) - fresh water lake(s)	Nan: (158, <class 'float'>)	Example: nan
Environment: Waste and recycling - municipal solid waste recycled annually	Nan: (89, <class 'float'>)	Example: nan
Environment: Waste and recycling - percent of municipal solid waste recycled	Nan: (89, <class 'float'>)	Example: nan
Environment: Major aquifers	Nan: (153, <class 'float'>)	Example: nan
Environment: Urbanization - note	Nan: (196, <class 'float'>)	Example: nan
Environment: Geoparks - total global geoparks and regional networks	Nan: (159, <class 'float'>)	Example: nan
Environment: Geoparks - global geoparks and regional networks	Nan: (159, <class 'float'>)	Example: nan
Environment: Environment - current issues - Baker Island	Nan: (206, <class 'float'>)	Example: nan
Environment: Environment - current issues - Howland Island	Nan: (206, <class 'float'>)	Example: nan
Environment: Environment - current issues - Jarvis Island	Nan: (206, <class 'float'>)	Example: nan
Environment: Environment - current issues - 	Nan: (206, <class 'float'>)	Example: nan
Environment: Environment - current issues - Johnston Atoll	Nan: (206, <class 'float'>)	Example: nan
Environment: Environment - current issues - Midway Islands	Nan: (206, <class 'float'>)	Example: nan
Environment: Environment - current issues - Kingman Reef	Nan: (206, <class 'float'>)	Example: nan
Environment: Environment - current issues - Palmyra Atoll	Nan: (206, <class 'float'>)	Example: nan
Environment: Climate - Baker, Howland, and Jarvis Islands	Nan: (206, <class 'float'>)	Example: nan
Environment: Climate - Johnston Atoll and Kingman Reef	Nan: (206, <class 'float'>)	Example: nan
Environment: Climate - Midway Islands	Nan: (206, <class 'float'>)	Example: nan
Environment: Climate - Palmyra Atoll	Nan: (206, <class 'float'>)	Example: nan
Environment: Food insecurity - widespread lack of access	Nan: (190, <class 'float'>)	Example: nan
Environment: Food insecurity - exceptional shortfall in aggregate food production/supplies	Nan: (202, <class 'float'>)	Example: nan
Environment: Climate - metropolitan France	Nan: (205, <class 'float'>)	Example: nan
Environment: Climate - French Guiana	Nan: (205, <class 'float'>)	Example: nan
Environment: Climate - Guadeloupe and Martinique	Nan: (205, <class 'float'>)	Example: nan
Environment: Climate - Mayotte	Nan: (205, <class 'float'>)	Example: nan
Environment: Climate - Reunion	Nan: (205, <class 'float'>)	Example: nan
Environment: Climate - Ile Amsterdam et Ile Saint-Paul	Nan: (206, <class 'float'>)	Example: nan
Environment: Climate - Iles Crozet	Nan: (206, <class 'float'>)	Example: nan
Environment: Climate - Iles Kerguelen	Nan: (206, <class 'float'>)	Example: nan
Environment: Climate - Iles Eparses	Nan: (206, <class 'float'>)	Example: nan
Environment: Air pollutants - note	Nan: (203, <class 'float'>)	Example: nan
Environment: Waste and recycling - note	Nan: (203, <class 'float'>)	Example: nan
Environment: Total water withdrawal - note	Nan: (203, <class 'float'>)	Example: nan
Environment: Total renewable water resources - note	Nan: (203, <class 'float'>)	Example: nan
Environment: Environment - current issues - note	Nan: (204, <class 'float'>)	Example: nan
Environment: Climate - note	Nan: (204, <class 'float'>)	Example: nan
Environment: Land use - note	Nan: (204, <class 'float'>)	Example: nan
Environment: Climate - Saint Helena	Nan: (206, <class 'float'>)	Example: nan
Environment: Climate - Ascension Island	Nan: (206, <class 'float'>)	Example: nan
Environment: Climate - Tristan da Cunha	Nan: (206, <class 'float'>)	Example: nan
Environment: World biomes - Types of Biomes	Nan: (205, <class 'float'>)	Example: nan
Environment: World biomes - Tundra biome	Nan: (205, <class 'float'>)	Example: nan
Environment: World biomes - Coniferous Forest biome	Nan: (205, <class 'float'>)	Example: nan
Environment: World biomes - Temperate Deciduous Forest biome	Nan: (205, <class 'float'>)	Example: nan
Environment: World biomes - Rainforest biome	Nan: (205, <class 'float'>)	Example: nan
Environment: World biomes - Grassland biome	Nan: (205, <class 'float'>)	Example: nan
Environment: World biomes - Shrubland biome	Nan: (205, <class 'float'>)	Example: nan
Environment: World biomes - Desert biome	Nan: (205, <class 'float'>)	Example: nan
Environment: Climate - ten driest places on Earth (average annual precipitation)	Nan: (205, <class 'float'>)	Example: nan
Environment: Climate - ten wettest places on Earth (average annual precipitation)	Nan: (205, <class 'float'>)	Example: nan
Environment: Climate - ten coldest places on Earth (lowest average monthly temperature)	Nan: (205, <class 'float'>)	Example: nan
Environment: Climate - ten hottest places on Earth (highest average monthly temperature)	Nan: (205, <class 'float'>)	Example: nan
Environment: Major lakes (area sq km) - top ten largest natural lakes	Nan: (205, <class 'float'>)	Example: nan
Environment: Major lakes (area sq km) - note 1	Nan: (205, <class 'float'>)	Example: nan
Environment: Major lakes (area sq km) - note 2	Nan: (205, <class 'float'>)	Example: nan
Environment: Major lakes (area sq km) - note 3	Nan: (205, <class 'float'>)	Example: nan
Environment: Major rivers (by length in km) - top ten longest rivers	Nan: (205, <class 'float'>)	Example: nan

/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/656387178.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  column_type = type(topic_df[column][0])
/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/656387178.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  example = topic_df[column][0]

# Cleanning of food production per country !

In [125]:
Production = pd.read_csv('/Users/placiermoise/Documents/BHTDataVisualizationCourse/data/Production_Crops_Livestock.csv')

# 1. Filtrer sur plusieurs années
years_to_keep = [2019,2020, 2021, 2022,2023]
Production_filtered = Production[Production['Year'].isin(years_to_keep)]

# 2. Créer une colonne pour nommer les futures colonnes du pivot
Production_filtered["column_prefix"] = (
    Production_filtered["Item"].str.replace(" ", "_") + "_" +
    Production_filtered["Element"].str.replace(" ", "_") + "_" +
    Production_filtered["Unit"].str.replace(" ", "_")
)

# 3. Pivot en moyennant les valeurs sur les années
Production_avg = Production_filtered.pivot_table(
    index="Area",
    columns="column_prefix",
    values="Value",
    aggfunc="mean"   # ICI on prend la moyenne sur les années
)

Production_avg =Production_avg.reset_index()

# Colonnes à garder en tête
fixed_cols = ['Area']

# Colonnes à trier
other_cols = sorted([col for col in Production_avg.columns if col not in fixed_cols])

# Réorganisation
Production_avg_pivoted = Production_avg[fixed_cols + other_cols]

/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/512381208.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  Production = pd.read_csv('/Users/placiermoise/Documents/BHTDataVisualizationCourse/data/Production_Crops_Livestock.csv')
/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/512381208.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Production_filtered["column_prefix"] = (

In [126]:
Land = pd.read_csv('/Users/placiermoise/Documents/BHTDataVisualizationCourse/data/Inputs_LandUse.csv', encoding="latin1") 
# 1. Filtrer sur plusieurs années
years_to_keep = [2019,2020, 2021, 2022,2023]
Land_filtered = Land[Land['Year'].isin(years_to_keep)]

# On crée une colonne qui combine item + element (ex: Figs_Area_Harvested)
Land_filtered["column_prefix"] = Land_filtered["Item"].str.replace(" ", "_") + "_" + Land_filtered["Element"].str.replace(" ", "_")+ "_" + Land_filtered["Unit"].str.replace(" ", "_")

# 3. Pivot en moyennant les valeurs sur les années
df_Land_avg = Land_filtered.pivot_table(
    index="Area",
    columns="column_prefix",
    values="Value",
    aggfunc="mean"   # ICI on prend la moyenne sur les années
)

df_Land_avg =df_Land_avg.reset_index()

# Colonnes à garder en tête
fixed_cols = ['Area']

# Colonnes à trier
other_cols = sorted([col for col in df_Land_avg.columns if col not in fixed_cols])

# Réorganisation
Land_avg_Pivoted = df_Land_avg[fixed_cols + other_cols]

/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/2527911239.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Land_filtered["column_prefix"] = Land_filtered["Item"].str.replace(" ", "_") + "_" + Land_filtered["Element"].str.replace(" ", "_")+ "_" + Land_filtered["Unit"].str.replace(" ", "_")

In [127]:
inputs_F = pd.read_csv('/Users/placiermoise/Documents/BHTDataVisualizationCourse/data/Inputs_FertilizersProduct.csv', encoding="latin1") 


inputs_F['Item'].unique()

array(['Ammonia, anhydrous', 'Ammonium nitrate (AN)', 'Ammonium sulphate',
       'Calcium ammonium nitrate (CAN) and other mixtures with calcium carbonate',
       'Diammonium phosphate (DAP)', 'Fertilizers n.e.c.',
       'Monoammonium phosphate (MAP)', 'NPK fertilizers',
       'Other nitrogenous fertilizers, n.e.c.', 'Other NP compounds',
       'Other phosphatic fertilizers, n.e.c.',
       'Other potassic fertilizers, n.e.c.', 'Phosphate rock',
       'PK compounds', 'Potassium chloride (muriate of potash) (MOP)',
       'Potassium nitrate',
       'Potassium sulphate (sulphate of potash) (SOP)', 'Sodium nitrate',
       'Superphosphates above 35%', 'Superphosphates, other', 'Urea',
       'Urea and ammonium nitrate solutions (UAN)', 'Other NK compounds'],
      dtype=object)

In [128]:
inputs_F = pd.read_csv('/Users/placiermoise/Documents/BHTDataVisualizationCourse/data/Inputs_FertilizersProduct.csv', encoding="latin1") 

# 1. Filtrer sur plusieurs années
years_to_keep = [2019,2020,2021, 2022,2023]
inputs_F_filtered = inputs_F[inputs_F['Year'].isin(years_to_keep)]

# On crée une colonne qui combine item + element (ex: Figs_Area_Harvested)
inputs_F_filtered["column_prefix"] = inputs_F_filtered["Item"].str.replace(" ", "_") + "_" + inputs_F_filtered["Element"].str.replace(" ", "_")+ "_" + inputs_F_filtered["Unit"].str.replace(" ", "_")

# 3. Pivot en moyennant les valeurs sur les années
inputs_F_avg = inputs_F_filtered.pivot_table(
    index="Area",
    columns="column_prefix",
    values="Value",
    aggfunc="mean"   # ICI on prend la moyenne sur les années
)

inputs_F_avg =inputs_F_avg.reset_index()

# Colonnes à garder en tête
fixed_cols = ['Area']

# Colonnes à trier
other_cols = sorted([col for col in inputs_F_avg.columns if col not in fixed_cols])

# Réorganisation
inputs_F_avg_Pivoted = inputs_F_avg[fixed_cols + other_cols]

inputs_F_avg_Pivoted

/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/4211492043.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inputs_F_filtered["column_prefix"] = inputs_F_filtered["Item"].str.replace(" ", "_") + "_" + inputs_F_filtered["Element"].str.replace(" ", "_")+ "_" + inputs_F_filtered["Unit"].str.replace(" ", "_")

column_prefix,Area,"Ammonia,_anhydrous_Agricultural_Use_t","Ammonia,_anhydrous_Export_quantity_t","Ammonia,_anhydrous_Export_value_1000_USD","Ammonia,_anhydrous_Import_quantity_t","Ammonia,_anhydrous_Import_value_1000_USD","Ammonia,_anhydrous_Production_t",Ammonium_nitrate_(AN)_Agricultural_Use_t,Ammonium_nitrate_(AN)_Export_quantity_t,Ammonium_nitrate_(AN)_Export_value_1000_USD,Ammonium_nitrate_(AN)_Import_quantity_t,Ammonium_nitrate_(AN)_Import_value_1000_USD,Ammonium_nitrate_(AN)_Production_t,Ammonium_sulphate_Agricultural_Use_t,Ammonium_sulphate_Export_quantity_t,Ammonium_sulphate_Export_value_1000_USD,Ammonium_sulphate_Import_quantity_t,Ammonium_sulphate_Import_value_1000_USD,Ammonium_sulphate_Production_t,Calcium_ammonium_nitrate_(CAN)_and_other_mixtures_with_calcium_carbonate_Agricultural_Use_t,Calcium_ammonium_nitrate_(CAN)_and_other_mixtures_with_calcium_carbonate_Export_quantity_t,Calcium_ammonium_nitrate_(CAN)_and_other_mixtures_with_calcium_carbonate_Export_value_1000_USD,Calcium_ammonium_nitrate_(CAN)_and_other_mixtures_with_calcium_carbonate_Import_quantity_t,Calcium_ammonium_nitrate_(CAN)_and_other_mixtures_with_calcium_carbonate_Import_value_1000_USD,Calcium_ammonium_nitrate_(CAN)_and_other_mixtures_with_calcium_carbonate_Production_t,Diammonium_phosphate_(DAP)_Agricultural_Use_t,Diammonium_phosphate_(DAP)_Export_quantity_t,Diammonium_phosphate_(DAP)_Export_value_1000_USD,Diammonium_phosphate_(DAP)_Import_quantity_t,Diammonium_phosphate_(DAP)_Import_value_1000_USD,Diammonium_phosphate_(DAP)_Production_t,Fertilizers_n.e.c._Agricultural_Use_t,Fertilizers_n.e.c._Export_quantity_t,Fertilizers_n.e.c._Export_value_1000_USD,Fertilizers_n.e.c._Import_quantity_t,Fertilizers_n.e.c._Import_value_1000_USD,Fertilizers_n.e.c._Production_t,Monoammonium_phosphate_(MAP)_Agricultural_Use_t,Monoammonium_phosphate_(MAP)_Export_quantity_t,Monoammonium_phosphate_(MAP)_Export_value_1000_USD,Monoammonium_phosphate_(MAP)_Import_quantity_t,Monoammonium_phosphate_(MAP)_Import_value_1000_USD,Monoammonium_phosphate_(MAP)_Production_t,NPK_fertilizers_Agricultural_Use_t,NPK_fertilizers_Export_quantity_t,NPK_fertilizers_Export_value_1000_USD,NPK_fertilizers_Import_quantity_t,NPK_fertilizers_Import_value_1000_USD,NPK_fertilizers_Production_t,Other_NK_compounds_Agricultural_Use_t,Other_NK_compounds_Production_t,Other_NP_compounds_Agricultural_Use_t,Other_NP_compounds_Export_quantity_t,Other_NP_compounds_Export_value_1000_USD,Other_NP_compounds_Import_quantity_t,Other_NP_compounds_Import_value_1000_USD,Other_NP_compounds_Production_t,"Other_nitrogenous_fertilizers,_n.e.c._Agricultural_Use_t","Other_nitrogenous_fertilizers,_n.e.c._Export_quantity_t","Other_nitrogenous_fertilizers,_n.e.c._Export_value_1000_USD","Other_nitrogenous_fertilizers,_n.e.c._Import_quantity_t","Other_nitrogenous_fertilizers,_n.e.c._Import_value_1000_USD","Other_nitrogenous_fertilizers,_n.e.c._Production_t","Other_phosphatic_fertilizers,_n.e.c._Agricultural_Use_t","Other_phosphatic_fertilizers,_n.e.c._Export_quantity_t","Other_phosphatic_fertilizers,_n.e.c._Export_value_1000_USD","Other_phosphatic_fertilizers,_n.e.c._Import_quantity_t","Other_phosphatic_fertilizers,_n.e.c._Import_value_1000_USD","Other_phosphatic_fertilizers,_n.e.c._Production_t","Other_potassic_fertilizers,_n.e.c._Agricultural_Use_t","Other_potassic_fertilizers,_n.e.c._Export_quantity_t","Other_potassic_fertilizers,_n.e.c._Export_value_1000_USD","Other_potassic_fertilizers,_n.e.c._Import_quantity_t","Other_potassic_fertilizers,_n.e.c._Import_value_1000_USD","Other_potassic_fertilizers,_n.e.c._Production_t",PK_compounds_Agricultural_Use_t,PK_compounds_Export_quantity_t,PK_compounds_Export_value_1000_USD,PK_compounds_Import_quantity_t,PK_compounds_Import_value_1000_USD,PK_compounds_Production_t,Phosphate_rock_Agricultural_Use_t,Phosphate_rock_Export_quantity_t,Phosphate_rock_Export_value_1000_USD,Phosphate_rock_Import_quantity_t,Phosphate_rock_Import_value_1000_USD,Phosphate_rock_Production_t,Potassium_chloride_(muriate_of_potash)_(MOP)_Agricultural_Use_t,Potassium_chloride_(muriate_of_potash)_(MOP)_Export_quantity_t,Potassium_chloride_(muriate_of_potash)_(MOP)_Export_value_1000_USD,Potassium_chloride_(muriate_of_potash)_(MOP)_Import_quantity_t,Potassium_chloride_(muriate_of_potash)_(MOP)_Import_value_1000_USD,Potassium_chloride_(muriate_of_potash)_(MOP)_Production_t,Potassium_nitrate_Agricultural_Use_t,Potassium_nitrate_Export_quantity_t,Potassium_nitrate_Export_value_1000_USD,Potassium_nitrate_Import_quantity_t,Potassium_nitrate_Import_value_1000_USD,Potassium_nitrate_Production_t,Potassium_sulphate_(sulphate_of_potash)_(SOP)_Agricultural_Use_t,Potassium_sulphate_(sulphate_of_potash)_(SOP)_Export_quantity_t,Potassium_sulphate_(sulphate_of_potash)_(SOP)_Export_value_1000_USD,Potassium_sulphate_(sulphate_of_potash)_(SOP)_Import_quantity_t,Potassium_sulphate_(sulphate_of_potash)_(SOP)_Import_value_1000_USD,Potassium_sulphate_(sulphate_of_potash)_(SOP)_Production_t,Sodium_nitrate_Agricultural_Use_t,Sodium_nitrate_Export_quantity_t,Sodium_nitrate_Export_value_1000_USD,Sodium_nitrate_Import_quantity_t,Sodium_nitrate_Import_value_1000_USD,Sodium_nitrate_Production_t,"Superphosphates,_other_Agricultural_Use_t","Superphosphates,_other_Export_quantity_t","Superphosphates,_other_Export_value_1000_USD","Superphosphates,_other_Import_quantity_t","Superphosphates,_other_Import_value_1000_USD","Superphosphates,_other_Production_t",Superphosphates_above_35%_Agricultural_Use_t,Superphosphates_above_35%_Export_quantity_t,Superphosphates_above_35%_Export_value_1000_USD,Superphosphates_above_35%_Import_quantity_t,Superphosphates_above_35%_Import_value_1000_USD,Superphosphates_above_35%_Production_t,Urea_Agricultural_Use_t,Urea_Export_quantity_t,Urea_Export_value_1000_USD,Urea_Import_quantity_t,Urea_Import_value_1000_USD,Urea_Production_t,Urea_and_ammonium_nitrate_solutions_(UAN)_Agricultural_Use_t,Urea_and_ammonium_nitrate_solutions_(UAN)_Export_quantity_t,Urea_and_ammonium_nitrate_solutions_(UAN)_Export_value_1000_USD,Urea_and_ammonium_nitrate_solutions_(UAN)_Import_quantity_t,Urea_and_ammonium_nitrate_solutions_(UAN)_Import_value_1000_USD,Urea_and_ammonium_nitrate_solutions_(UAN)_Production_t
0,Afghanistan,NaN,NaN,NaN,32.983333,5.546667e+00,NaN,NaN,34.00,10.3300,NaN,NaN,NaN,NaN,NaN,NaN,1320.6400,3.021000e+02,NaN,NaN,NaN,NaN,33.600000,15.740000,NaN,NaN,NaN,NaN,19392.625000,9.419995e+03,NaN,NaN,10.806667,1.986667,1224.6950,462.9450,NaN,NaN,NaN,NaN,676.0825,2.868000e+02,NaN,NaN,0.010000,1.000000e-02,474.5500,2.779867e+02,NaN,NaN,NaN,NaN,NaN,NaN,34280.4725,1.305975e+04,NaN,NaN,3.9000,10.2900,114.4375,42.3425,NaN,NaN,17.02,12.0000,156.360000,99.3800,NaN,NaN,NaN,NaN,21.456667,55.6800,NaN,NaN,NaN,NaN,12.8600,94.3600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,262.92,7.718000e+01,16.873333,2.653333e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.3600,21.443333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14135.4100,2450.2600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.505333e+02,4.796233e+02,170783.2875,4.081417e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa (excluding intra-trade),NaN,NaN,9.204083e+05,NaN,1.109601e+06,NaN,NaN,NaN,50490.6150,NaN,364355.3650,NaN,NaN,NaN,53755.2750,NaN,2.004241e+05,NaN,NaN,NaN,1.994707e+03,NaN,92089.637500,NaN,NaN,NaN,1.997239e+06,NaN,1.939035e+05,NaN,NaN,NaN,14427.665000,NaN,310647.6775,NaN,NaN,NaN,1.696514e+06,NaN,2.050055e+05,NaN,NaN,NaN,1.915177e+05,NaN,6.139277e+05,NaN,NaN,NaN,NaN,NaN,189924.4000,NaN,3.839455e+04,NaN,NaN,NaN,31926.7775,NaN,208994.3975,NaN,NaN,NaN,225158.7800,NaN,6164.8975,NaN,NaN,NaN,1631.1050,NaN,38537.3600,NaN,NaN,NaN,861.4675,NaN,19600.4900,NaN,NaN,NaN,2.406077e+06,NaN,1311.8025,NaN,NaN,NaN,6.927430e+03,NaN,4.862585e+05,NaN,NaN,NaN,1072.4975,NaN,84437.2700,NaN,NaN,NaN,58542.2725,NaN,111963.447500,NaN,NaN,NaN,902.4800,NaN,5575.145000,NaN,NaN,NaN,279100.7475,NaN,8736.3850,NaN,NaN,NaN,611108.5125,NaN,22660.285000,NaN,NaN,NaN,3.630432e+06,NaN,1.282114e+06,NaN,NaN,NaN,15755.4500,NaN,3352.982500,NaN
2,Albania,NaN,NaN,NaN,4.650000,7.917500e+00,NaN,21249.75,33881.60,16769.2900,16273.5775,4456.5450,NaN,1107.75,NaN,NaN,1927.4750,7.331625e+02,NaN,470.0,NaN,NaN,2890.537500,1088.157500,NaN,12288.25,NaN,NaN,11284.645000,4.297943e+03,NaN,NaN,3.325000,8.760000,2984.0600,3689.0350,NaN,NaN,NaN,NaN,379.3600,1.829025e+02,NaN,30838.0,19.523333,1.936333e+01,35065.8100,1.944174e+04,NaN,NaN,NaN,NaN,NaN,NaN,1639.3575,9.044600e+02,NaN,NaN,48.0000,7.6800,7403.3400,4013.0275,NaN,NaN,15.00,2.7400,4195.445000,1710.6450,NaN,NaN,NaN,NaN,33.635000,42.8825,NaN,NaN,NaN,NaN,55.6525,114.4000,NaN,NaN,NaN,NaN,5.9575,4.6425,NaN,438.75,NaN,NaN,722.942500,3.266050e+02,NaN,NaN,NaN,NaN,130.7750,139.1700,NaN,185.25,NaN,NaN,220.2650,133.322500,NaN,14.0,NaN,NaN,11.187500,24.062500,NaN,NaN,NaN,NaN,172.4475,52.1875,NaN,18358.0,NaN,NaN,75.733333,37.133333,NaN,36205.5,5.599523e+03,2.618067e+03,30176.8000,1.013726e+04,NaN,NaN,NaN,NaN,0.760000,1.045000,NaN
3,Algeria,NaN,2063834.17,1.223399e+06,9.200000,1.453000e+01,NaN,NaN,0.05,0.4000,5252.3775,1536.1350,NaN,NaN,NaN,NaN,20488.2875,3.548003e+03,NaN,NaN,8800.0800,1.825460e+03,42.440000,81.420000,NaN,NaN,9870.78,6.783230e+03,3031.337500,1.930707e+03,NaN,NaN,2858.806667,318.703333,16853.0000,26271.1025,NaN,NaN,29.650000,8.020000e+00,43203.6475,2.290846e+04,NaN,NaN,53.000000,2.177000e+01,133458.4700,6.807390e+04,NaN,NaN,NaN,NaN,24.82,2.7500,6454.7700,3.690965e+03,NaN,NaN,4662.3150,1384.2100,6391.9175,3585.7625,NaN,NaN,24139.27,1521.9750,163.906667,99.4900,NaN,NaN,NaN,NaN,160.777500,316.9500,NaN,NaN,NaN,NaN,6801.0475,4692.1975,NaN,NaN,2011451.38,2.081929e+05,73.8600,31.9750,NaN,NaN,57.00,1.925000e+01,4734.110000,2.641050e+03,NaN,NaN,NaN,NaN,2985.4025,3293.3500,NaN,NaN,NaN,NaN,7463.5950,5667.435000,NaN,NaN,NaN,NaN,259.520000,126.867500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5335.813333,2826.610000,NaN,NaN,4.040823e+06,1.842782e+06,31218.0100,8.709237e+03,NaN,NaN,68707.50,21841.7600,133.706667,54.053333,NaN
4,Americas (excluding intra-trade),NaN,NaN,1.077821e+06,NaN,3.196422e+05,NaN,NaN,NaN,15684.0125,NaN,762851.9450,NaN,NaN,NaN,20843.7650,NaN,1.255799e+06,NaN,NaN,NaN,8.033092e+03,NaN,263253.852500,NaN,NaN,NaN,1.204919e+05,NaN,1.107218e+06,NaN,NaN,NaN,154439.437500,NaN,528973.0225,NaN,NaN,NaN,1.438222e+05,NaN,3.769252e+06,NaN,NaN,NaN,7.726609e+04,NaN,1.363741e+06,NaN,NaN,NaN,NaN,NaN,36509.8975,NaN,1.051956e+06,NaN,NaN,NaN,26733.0850,NaN,652806.3200,NaN,NaN,NaN,19817.1125,NaN,105803.1725,NaN,NaN,NaN,59870.9125,NaN,216296.2275,NaN,NaN,NaN,6266.1550,NaN,71154.7225,NaN,NaN,NaN,3.017518e+04,NaN,357861.2900,NaN,NaN,NaN,2.824005e+06,NaN,4.161929e+06,NaN,NaN,NaN,260754.6400,NaN,39946.7725,NaN,NaN,NaN,8494.6775,NaN,248477.410000,NaN,NaN,NaN,39498.4925,NaN,12196.735000,NaN,NaN,NaN,144.2125,NaN,410572.4400,NaN,NaN,NaN,3305.3325,NaN,753554.800000,NaN,NaN,NaN,8.108380e+04,NaN,6.665934e+06,NaN,NaN,NaN,347623.4350,NaN,453820.947500,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,Western Asia (excluding intra-trade),NaN,NaN,2.034358e+06,NaN,4.659635e+05,NaN,NaN,NaN,258781.2275,NaN,125090.5000,NaN,NaN,NaN,18892.3425,NaN,1.869940e+05,NaN,NaN,NaN,1.403857e+05,NaN,5053.352500,NaN,NaN,NaN,1.920619e+06,NaN,1.799416e+05,NaN,NaN,NaN,458886.935000,NaN,72613.2650,NaN,NaN,NaN,8.038639e+05,NaN,1.528389e+05,NaN,NaN,NaN,3.296694e+05,NaN,2.164949e+05,NaN,NaN,NaN,NaN,NaN,210304.2600,NaN,1.373144e+05,NaN,NaN,NaN,567380.3725,NaN,65110.6675,NaN,NaN,NaN,59180.6225,NaN,3502.3925,NaN,NaN,NaN,254141.9750,NaN,8564.2975,NaN,NaN,NaN,87236.8775,NaN,6192.1150,NaN,NaN,NaN,9.631620e+05,NaN,181047.6200,NaN,NaN,NaN,2.058675e+06,NaN,9.032662e+04,NaN,NaN,NaN,225896.8000,NaN,69774.8850,NaN,NaN,NaN,28650.1275,NaN,40479.287500,NaN,NaN,NaN,273.5925,NaN,40550.475000,NaN,NaN,NaN,101441.2875,NaN,3843.8875,NaN,NaN,NaN,352827.9275,NaN,37150.525000,NaN,NaN,NaN,6.873382e+06,NaN,8.453175e+05,NaN,NaN,NaN,12040.5900,NaN,15169.560000,NaN
227,Western Europe (excluding intra-trade),NaN,NaN,2.090236e+05,NaN,9.557434e+05,NaN,NaN,NaN,86128.6250,NaN,56705.6850,NaN,NaN,NaN,286172.6975,NaN,8.082987e+04,NaN,NaN,NaN,1.022610e+06,NaN,408481.862500,NaN,NaN,NaN,4.681321e+04,NaN,2.868109e+05,NaN,NaN,NaN,240657.827500,NaN,91364.0475,NaN,NaN,NaN,5.865401e+04,NaN,7.221833e+04,NaN,NaN,NaN,1.021036e+06,NaN,1.485482e+05,NaN,NaN,NaN,NaN,NaN,152552.1700,NaN,3.675636e+04,NaN,NaN,NaN,334588.2300,NaN,164229.5300,NaN,NaN,NaN,7641.9350,NaN,33121.4800,NaN,NaN,NaN,84522.8125,NaN,25630.6850,NaN,NaN,NaN,77915.5500,NaN,25592.0225,NaN,NaN,NaN,6.043898e+03,NaN,247194.4350,NaN,NaN,NaN,1.214668e+06,NaN,5.573931e+05,NaN,NaN,NaN,95830.0475,NaN,173763.6475,NaN,NaN,NaN,389470.6325,NaN,16977.707500,NaN,NaN,NaN,43779.9475,NaN,8897.517500,NaN,NaN,NaN,9417.5775,NaN,10803.8750,NaN,NaN,NaN,29213.9325,NaN,126727.762500,NaN,NaN,NaN,8.101124e+05,NaN,9.273935e+05,NaN,NaN,NaN,127159.6975,NaN,496462.192500,NaN
228,Yemen,NaN,NaN,NaN,15.500000,1.500000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2827.5300,3.144300e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,195.020000,1.735000e+01,NaN,NaN,NaN,NaN,26861.9300,9020.9100,NaN,NaN,NaN,NaN,220.0000,3.998000e+01,NaN,NaN,184.080000,2.502233e+02,8164.9100,2.170420e+03,NaN,NaN,NaN,NaN,NaN,NaN,334.2100,7.988000e+01,NaN,NaN,0.0300,0.0300,217.2000,86.5000,NaN,NaN,NaN,NaN,281.640000,78.3600,NaN,NaN,NaN,NaN,631.850000,246.8100,NaN,NaN,NaN,NaN,130.0000,23.4200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.500000,6.310000e+00,NaN,NaN,0.01,0.2000,3.3800,1.4400,NaN,NaN,26.07,6.2400,76.0000,7.670000,NaN,NaN,0.00,0.1000,20.000000,6.510000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15486.9600,4.345270e+03,NaN,NaN,NaN,NaN,177.000000,43.730000,NaN
229,Zambia,NaN,0.70,4.030000e+00,107.772500,5.899750e+01,NaN,NaN,7551.13,3502.8425,128368.6750,67763.2425,NaN,NaN,465.17,88.1100,22015.1200,6.541975e+03,NaN,NaN,6219.0175,3.704500e+03,4145.706667,844.946667,NaN,NaN,NaN,NaN,5728.755000,6.082278e+03,NaN,NaN,485.095000,314.120000,58265.7600,66212.3575,NaN,NaN,14.536667,8.666667e+00,24352.3025,1.615343e+04,NaN,203488.5,1866.817500,1.584330e+03,179977.6725,1.078905e+05,NaN,NaN,NaN,NaN,141.57,110.7800,6268.8075,3.786323e+03,NaN,NaN,16317.1000,9402.8550,81325.0300,57964.6150,NaN,NaN,NaN,NaN,3097.592500,1416.8525,NaN,NaN,NaN,NaN,5838.932500,3953.4850,NaN,NaN,3.05,5.3200,4577.8575,2377.6650,NaN,NaN,NaN,NaN,0.0500,0.6900,NaN,NaN,0.01,1.510000e+00,10006.440000,4.619335e+03,NaN,NaN,NaN,NaN,23.2525,35.7375,NaN,NaN,NaN,NaN,8038.8950,6799.605000,NaN,NaN,12.80,11.4800,689.473333,611.223333,NaN,NaN,NaN,NaN,1046.6950,181.5450,NaN,NaN,NaN,NaN,342.276667,97.533333,NaN,175770.5,3.873440e+03,1.221845e+03,266166.1375,1.274094e+05,NaN,NaN,33.98,5.7400,1368.180000,1275.386667,NaN
230,Zimbabwe,NaN,0.11,2.000000e-01,9497.422500,7.810642e+03,NaN,NaN,150.90,40.6500,92983.0800,53236.3700,NaN,NaN,NaN,NaN,32635.2675,1.592938e+04,NaN,NaN,NaN,NaN,53131.797500,33269.960000,NaN,NaN,NaN,NaN,1549.603333,1.744833e+03,NaN,NaN,2547.572500,621.872500,12527.4375,11667.8525,NaN,NaN,NaN,NaN,91683.2175,6.910952e+04,NaN,NaN,2522.000000,1.255765e+03,18748.2250,1.094901e+04,NaN,NaN,NaN,NaN,120.00,9.3600,318.0650,3.122050e+02,NaN,NaN,40.8125,119.0375,29024.2625,21285.7300,NaN,NaN,1294.00,90.4450,860.222500,598.4750,NaN,NaN,18.37,62.0150,7212.915000,4436.8000,NaN,NaN,NaN,NaN,124.1100,221.7850,NaN,NaN,9940.00,6.386800e+02,0.5325,1.3100,NaN,NaN,NaN,NaN,47036.152500,3.242681e+04,NaN,NaN,NaN,NaN,26.9900,30.5525,NaN,NaN,NaN,NaN,21500.9325,19623.865000,NaN,NaN,28.23,18.4500,1033.732500,681.800000,NaN,NaN,NaN,NaN,4159.1600,3003.6250,NaN,NaN,NaN,NaN,0.780000,12.705000,NaN,NaN,9.150000e+02,3.689500e+02,87734.0825,5.375216e+04,NaN,NaN,NaN,NaN,0.010000,0.010000,NaN

In [129]:
Machinery = pd.read_csv('/Users/placiermoise/Documents/BHTDataVisualizationCourse/data/Investment_Machinery.csv', encoding="latin1") 
Machinery = Machinery[Machinery['Element'] == "In Use"]
# 1. Filtrer sur plusieurs années
years_to_keep = [2009,2008,2007, 2006]
Machinery_filtered = Machinery[Machinery['Year'].isin(years_to_keep)]

# On crée une colonne qui combine item + element (ex: Figs_Area_Harvested)
Machinery_filtered["column_prefix"] = Machinery_filtered["Item"].str.replace(" ", "_") + "_" + Machinery_filtered["Element"].str.replace(" ", "_")+ "_" + Machinery_filtered["Unit"].str.replace(" ", "_")

# 3. Pivot en moyennant les valeurs sur les années
Machinery_avg = Machinery_filtered.pivot_table(
    index="Area",
    columns="column_prefix",
    values="Value",
    aggfunc="mean"   # ICI on prend la moyenne sur les années
)

Machinery_avg =Machinery_avg.reset_index()

# Colonnes à garder en tête
fixed_cols = ['Area']

# Colonnes à trier
other_cols = sorted([col for col in Machinery_avg.columns if col not in fixed_cols])

# Réorganisation
Machinery_avg_Pivoted = Machinery_avg[fixed_cols + other_cols]

/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/3825024113.py:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  Machinery = pd.read_csv('/Users/placiermoise/Documents/BHTDataVisualizationCourse/data/Investment_Machinery.csv', encoding="latin1")
/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/3825024113.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Machinery_filtered["column_prefix"] = Machinery_filtered["Item"].str.replace(" ", "_") + "_" + Machinery_filtered["Element"].str.replace(" ", "_")+ "_" + Machinery_filtered["Unit"].str.replace(" ", "_")

In [130]:
Inputs_P = pd.read_csv('/Users/placiermoise/Documents/BHTDataVisualizationCourse/data/Inputs_Pesticides.csv', encoding="latin1") 

# 1. Filtrer sur plusieurs années
years_to_keep = [2019,2020, 2021, 2022,2023]

Inputs_P_filtered = Inputs_P[Inputs_P['Year'].isin(years_to_keep)]

# On crée une colonne qui combine item + element (ex: Figs_Area_Harvested)
Inputs_P_filtered["column_prefix"] = Inputs_P_filtered["Item"].str.replace(" ", "_") + "_" + Inputs_P_filtered["Element"].str.replace(" ", "_")+ "_" + Inputs_P_filtered["Unit"].str.replace(" ", "_")

# 3. Pivot en moyennant les valeurs sur les années
Inputs_P_avg = Inputs_P_filtered.pivot_table(
    index="Area",
    columns="column_prefix",
    values="Value",
    aggfunc="mean"   # ICI on prend la moyenne sur les années
)

Inputs_P_avg =Inputs_P_avg.reset_index()

# Colonnes à garder en tête
fixed_cols = ['Area']

# Colonnes à trier
other_cols = sorted([col for col in Inputs_P_avg.columns if col not in fixed_cols])

# Réorganisation
Inputs_P_avg_Pivoted = Inputs_P_avg[fixed_cols + other_cols]

/var/folders/5y/cg3f72r56ndb2p52h64tts3m0000gn/T/ipykernel_97510/98285152.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Inputs_P_filtered["column_prefix"] = Inputs_P_filtered["Item"].str.replace(" ", "_") + "_" + Inputs_P_filtered["Element"].str.replace(" ", "_")+ "_" + Inputs_P_filtered["Unit"].str.replace(" ", "_")

In [132]:
Production_avg_pivoted_I = Production_avg_pivoted.set_index("Area")

Land_avg_Pivoted_I = Land_avg_Pivoted.set_index("Area")

inputs_F_avg_Pivoted_I = inputs_F_avg_Pivoted.set_index("Area")

Machinery_avg_Pivoted_I = Machinery_avg_Pivoted.set_index("Area")

Inputs_P_avg_Pivoted_I = Inputs_P_avg_Pivoted.set_index("Area")

FAO_Dataset_19_23 =  pd.concat([Production_avg_pivoted_I, Land_avg_Pivoted_I,inputs_F_avg_Pivoted_I,Inputs_P_avg_Pivoted_I,Machinery_avg_Pivoted_I], axis=1).reset_index()

FAO_Dataset_19_23

column_prefix,Area,"Abaca,_manila_hemp,_raw_Area_harvested_ha","Abaca,_manila_hemp,_raw_Production_t","Abaca,_manila_hemp,_raw_Yield_kg/ha","Agave_fibres,_raw,_n.e.c._Area_harvested_ha","Agave_fibres,_raw,_n.e.c._Production_t","Agave_fibres,_raw,_n.e.c._Yield_kg/ha","Almonds,_in_shell_Area_harvested_ha","Almonds,_in_shell_Production_t","Almonds,_in_shell_Yield_kg/ha","Anise,_badian,_coriander,_cumin,_caraway,_fennel_and_juniper_berries,_raw_Area_harvested_ha","Anise,_badian,_coriander,_cumin,_caraway,_fennel_and_juniper_berries,_raw_Production_t","Anise,_badian,_coriander,_cumin,_caraway,_fennel_and_juniper_berries,_raw_Yield_kg/ha",Apples_Area_harvested_ha,Apples_Production_t,Apples_Yield_kg/ha,Apricots_Area_harvested_ha,Apricots_Production_t,Apricots_Yield_kg/ha,Areca_nuts_Area_harvested_ha,Areca_nuts_Production_t,Areca_nuts_Yield_kg/ha,Artichokes_Area_harvested_ha,Artichokes_Production_t,Artichokes_Yield_kg/ha,Asparagus_Area_harvested_ha,Asparagus_Production_t,Asparagus_Yield_kg/ha,Asses_Stocks_An,Avocados_Area_harvested_ha,Avocados_Production_t,Avocados_Yield_kg/ha,"Bambara_beans,_dry_Area_harvested_ha","Bambara_beans,_dry_Production_t","Bambara_beans,_dry_Yield_kg/ha",Bananas_Area_harvested_ha,Bananas_Production_t,Bananas_Yield_kg/ha,Barley_Area_harvested_ha,Barley_Production_t,Barley_Yield_kg/ha,"Beans,_dry_Area_harvested_ha","Beans,_dry_Production_t","Beans,_dry_Yield_kg/ha","Beef_and_Buffalo_Meat,_primary_Producing_Animals/Slaughtered_An","Beef_and_Buffalo_Meat,_primary_Production_t","Beef_and_Buffalo_Meat,_primary_Yield/Carcass_Weight_kg/An","Beer_of_barley,_malted_Production_t",Bees_Stocks_No,Beeswax_Production_t,Blueberries_Area_harvested_ha,Blueberries_Production_t,Blueberries_Yield_kg/ha,"Brazil_nuts,_in_shell_Production_t","Broad_beans_and_horse_beans,_dry_Area_harvested_ha","Broad_beans_and_horse_beans,_dry_Production_t","Broad_beans_and_horse_beans,_dry_Yield_kg/ha","Broad_beans_and_horse_beans,_green_Area_harvested_ha","Broad_beans_and_horse_beans,_green_Production_t","Broad_beans_and_horse_beans,_green_Yield_kg/ha",Buckwheat_Area_harvested_ha,Buckwheat_Production_t,Buckwheat_Yield_kg/ha,Buffalo_Stocks_An,"Buffalo_fat,_unrendered_Producing_Animals/Slaughtered_An","Buffalo_fat,_unrendered_Production_t",Butter_and_Ghee_Production_t,Butter_and_ghee_of_sheep_milk_Production_t,Butter_of_buffalo_milk_Production_t,Butter_of_cow_milk_Production_t,"Buttermilk,_dry_Production_t",Cabbages_Area_harvested_ha,Cabbages_Production_t,Cabbages_Yield_kg/ha,Camels_Stocks_An,Canary_seed_Area_harvested_ha,Canary_seed_Production_t,Canary_seed_Yield_kg/ha,Cantaloupes_and_other_melons_Area_harvested_ha,Cantaloupes_and_other_melons_Production_t,Cantaloupes_and_other_melons_Yield_kg/ha,Carrots_and_turnips_Area_harvested_ha,Carrots_and_turnips_Production_t,Carrots_and_turnips_Yield_kg/ha,"Cashew_nuts,_in_shell_Area_harvested_ha","Cashew_nuts,_in_shell_Production_t","Cashew_nuts,_in_shell_Yield_kg/ha",Cashewapple_Area_harvested_ha,Cashewapple_Production_t,Cashewapple_Yield_kg/ha,"Cassava,_fresh_Area_harvested_ha","Cassava,_fresh_Production_t","Cassava,_fresh_Yield_kg/ha",Castor_oil_seeds_Area_harvested_ha,Castor_oil_seeds_Production_t,Castor_oil_seeds_Yield_kg/ha,Cattle_Stocks_An,Cattle_and_Buffaloes_Stocks_An,"Cattle_fat,_unrendered_Producing_Animals/Slaughtered_An","Cattle_fat,_unrendered_Production_t",Cauliflowers_and_broccoli_Area_harvested_ha,Cauliflowers_and_broccoli_Production_t,Cauliflowers_and_broccoli_Yield_kg/ha,"Cereals,_primary_Area_harvested_ha","Cereals,_primary_Production_t","Cereals,_primary_Yield_kg/ha",Cereals_n.e.c._Area_harvested_ha,Cereals_n.e.c._Production_t,Cereals_n.e.c._Yield_kg/ha,Cheese_(All_Kinds)_Production_t,"Cheese_from_milk_of_buffalo,_fresh_or_processed_Production_t","Cheese_from_milk_of_goats,_fresh_or_processed_Production_t","Cheese_from_milk_of_sheep,_fresh_or_processed_Production_t",Cheese_from_skimmed_cow_milk_Production_t,Cheese_from_whole_cow_milk_Production_t,Cherries_Area_harvested_ha,Cherries_Production_t,Cherries_Yield_kg/ha,"Chestnuts,_in_shell_Area_harvested_ha","Chestnuts,_in_shell_Production_t","Chestnuts,_in_shell_Yield_kg/ha","Chick_peas,_dry_Area_harvested_ha","Chick_peas,_dry_Production_t","Chick_peas,_dry_Yield_kg/ha",Chickens_Stocks_1000_An,Chicory_roots_Area_harvested_ha,Chicory_roots_Production_t,Chicory_roots_Yield_kg/ha,"Chillies_and_peppers,_dry_(Capsicum_spp.,_Pimenta_spp.),_raw_Area_harvested_ha","Chillies_and_peppers,_dry_(Capsicum_spp.,_Pimenta_spp.),_raw_Production_t","Chillies_and_peppers,_dry_(Capsicum_spp.,_Pimenta_spp.),_raw_Yield_kg/ha","Chillies_and_peppers,_green_(Capsicum_spp._and_Pimenta_spp.)_Area_harvested_ha","Chillies_and_peppers,_green_(Capsicum_spp._and_Pimenta_spp.)_Production_t","Chillies_and_peppers,_green_(Capsicum_spp._and_Pimenta_spp.)_Yield_kg/ha","Cinnamon_and_cinnamon-tree_flowers,_raw_Area_harvested_ha","Cinnamon_and_cinnamon-tree_flowers,_raw_Production_t","Cinnamon_and_cinnamon-tree_flowers,_raw_Yield_kg/ha","Citrus_Fruit,_Total_Area_harvested_ha","Citrus_Fruit,_Total_Production_t","Citrus_Fruit,_Total_Yield_kg/ha","Cloves_(whole_stems),_raw_Area_harvested_ha","Cloves_(whole_stems),_raw_Production_t","Cloves_(whole_stems),_raw_Yield_kg/ha",Cocoa_beans_Area_harvested_ha,Cocoa_beans_Production_t,Cocoa_beans_Yield_kg/ha,Coconut_oil_Production_t,"Coconuts,_in_shell_Area_harvested_ha","Coconuts,_in_shell_Production_t","Coconuts,_in_shell_Yield_kg/ha","Coffee,_green_Area_harvested_ha","Coffee,_green_Production_t","Coffee,_green_Yield_kg/ha","Coir,_raw_Production_t","Cotton_lint,_ginned_Production_t",Cotton_seed_Production_t,Cottonseed_oil_Production_t,"Cow_peas,_dry_Area_harvested_ha","Cow_peas,_dry_Production_t","Cow_peas,_dry_Yield_kg/ha",Cranberries_Area_harvested_ha,Cranberries_Production_t,Cranberries_Yield_kg/ha,"Cream,_fresh_Production_t",Cucumbers_and_gherkins_Area_harvested_ha,Cucumbers_and_gherkins_Production_t,Cucumbers_and_gherkins_Yield_kg/ha,Currants_Area_harvested_ha,Currants_Production_t,Currants_Yield_kg/ha,Dates_Area_harvested_ha,Dates_Production_t,Dates_Yield_kg/ha,Ducks_Stocks_1000_An,"Edible_offal_of_buffalo,_fresh,_chilled_or_frozen_Producing_Animals/Slaughtered_An","Edible_offal_of_buffalo,_fresh,_chilled_or_frozen_Production_t","Edible_offal_of_cattle,_fresh,_chilled_or_frozen_Producing_Animals/Slaughtered_An","Edible_offal_of_cattle,_fresh,_chilled_or_frozen_Production_t","Edible_offal_of_goat,_fresh,_chilled_or_frozen_Producing_Animals/Slaughtered_An","Edible_offal_of_goat,_fresh,_chilled_or_frozen_Production_t","Edible_offal_of_pigs,_fresh,_chilled_or_frozen_Producing_Animals/Slaughtered_An","Edible_offal_of_pigs,_fresh,_chilled_or_frozen_Production_t","Edible_offal_of_sheep,_fresh,_chilled_or_frozen_Producing_Animals/Slaughtered_An","Edible_offal_of_sheep,_fresh,_chilled_or_frozen_Production_t","Edible_offals_of_camels_and_other_camelids,_fresh,_chilled_or_frozen_Producing_Animals/Slaughtered_An","Edible_offals_of_camels_and_other_camelids,_fresh,_chilled_or_frozen_Production_t","Edible_offals_of_horses_and_other_equines,__fresh,_chilled_or_frozen_Producing_Animals/Slaughtered_An","Edible_offals_of_horses_and_other_equines,__fresh,_chilled_or_frozen_Production_t","Edible_roots_and_tubers_with_high_starch_or_inulin_content,_n.e.c.,_fresh_Area_harvested_ha","Edible_roots_and_tubers_with_high_starch_or_inulin_content,_n.e.c.,_fresh_Production_t","Edible_roots_and_tubers_with_high_starch_or_inulin_content,_n.e.c.,_fresh_Yield_kg/ha",Eggplants_(aubergines)_Area_harvested_ha,Eggplants_(aubergines)_Production_t,Eggplants_(aubergines)_Yield_kg/ha,Eggs_Primary_Laying_1000_An,Eggs_Primary_Production_t,Eggs_Primary_Yield/Carcass_Weight_g/An,"Eggs_from_other_birds_in_shell,_fresh,_n.e.c._Laying_1000_An","Eggs_from_other_birds_in_shell,_fresh,_n.e.c._Production_1000_No","Eggs_from_other_birds_in_shell,_fresh,_n.e.c._Production_t","Eggs_from_other_birds_in_shell,_fresh,_n.e.c._Yield/Carcass_Weight_g/An","Eggs_from_other_birds_in_shell,_fresh,_n.e.c._Yield_No/An",Evaporated_&_Condensed_Milk_Production_t,Fat_of_camels_Producing_Animals/Slaughtered_An,Fat_of_camels_Production_t,Fat_of_pigs_Producing_Animals/Slaughtered_An,Fat_of_pigs_Production_t,"Fibre_Crops,_Fibre_Equivalent_Area_harvested_ha","Fibre_Crops,_Fibre_Equivalent_Production_t","Fibre_Crops,_Fibre_Equivalent_Yield_kg/ha",Figs_Area_harvested_ha,Figs_Production_t,Figs_Yield_kg/ha,"Flax,_raw_or_retted_Area_harvested_ha","Flax,_raw_or_retted_Production_t","Flax,_raw_or_retted_Yield_kg/ha",Fonio_Area_harvested_ha,Fonio_Production_t,Fonio_Yield_kg/ha,Fruit_Primary_Area_harvested_ha,Fruit_Primary_Production_t,Fruit_Primary_Yield_kg/ha,"Game_meat,_fresh,_chilled_or_frozen_Production_t",Geese_Stocks_1000_An,Ghee_from_buffalo_milk_Production_t,Ghee_from_cow_milk_Production_t,"Ginger,_raw_Area_harvested_ha","Ginger,_raw_Production_t","Ginger,_raw_Yield_kg/ha","Goat_fat,_unrendered_Producing_Animals/Slaughtered_An","Goat_fat,_unrendered_Production_t",Goats_Stocks_An,Gooseberries_Area_harvested_ha,Gooseberries_Production_t,Gooseberries_Yield_kg/ha,Grapes_Area_harvested_ha,Grapes_Production_t,Grapes_Yield_kg/ha,Green_corn_(maize)_Area_harvested_ha,Green_corn_(maize)_Production_t,Green_corn_(maize)_Yield_kg/ha,Green_garlic_Area_harvested_ha,Green_garlic_Production_t,Green_garlic_Yield_kg/ha,"Green_tea_(not_fermented),_black_tea_(fermented)_and_partly_fermented_tea,_in_immediate_packings_of_a_content_not_exceeding_3_kg_Production_t",Groundnut_oil_Production_t,"Groundnuts,_excluding_shelled_Area_harvested_ha","Groundnuts,_excluding_shelled_Production_t","Groundnuts,_excluding_shelled_Yield_kg/ha","Hazelnuts,_in_shell_Area_harvested_ha","Hazelnuts,_in_shell_Production_t","Hazelnuts,_in_shell_Yield_kg/ha",Hempseed_Area_harvested_ha,Hempseed_Production_t,Hempseed_Yield_kg/ha,"Hen_eggs_in_shell,_fresh_Laying_1000_An","Hen_eggs_in_shell,_fresh_Production_1000_No","Hen_eggs_in_shell,_fresh_Production_t","Hen_eggs_in_shell,_fresh_Yield/Carcass_Weight_g/An","Hen_eggs_in_shell,_fresh_Yield_No/An",Hop_cones_Area_harvested_ha,Hop_cones_Production_t,Hop_cones_Yield_kg/ha,"Horse_meat,_fresh_or_chilled_Producing_Animals/Slaughtered_An","Horse_meat,_fresh_or_chilled_Production_t","Horse_meat,_fresh_or_chilled_Yield/Carcass_Weight_kg/An",Horses_Stocks_An,Jojoba_seeds_Area_harvested_ha,Jojoba_seeds_Production_t,Jojoba_seeds_Yield_kg/ha,"Jute,_raw_or_retted_Area_harvested_ha","Jute,_raw_or_retted_Production_t","Jute,_raw_or_retted_Yield_kg/ha","Kapok_fibre,_raw_Production_t",Kapok_fruit_Area_harvested_ha,Kapok_fruit_Production_t,Kapok_fruit_Yield_kg/ha,Kapokseed_in_shell_Production_t,Karite_nuts_(sheanuts)_Area_harvested_ha,Karite_nuts_(sheanuts)_Production_t,Karite_nuts_(sheanuts)_Yield_kg/ha,"Kenaf,_and_other_textile_bast_fibres,_raw_or_retted_Area_harvested_ha","Kenaf,_and_other_textile_bast_fibres,_raw_or_retted_Production_t","Kenaf,_and_other_textile_bast_fibres,_raw_or_retted_Yield_kg/ha",Kiwi_fruit_Area_harvested_ha,Kiwi_fruit_Production_t,Kiwi_fruit_Yield_kg/ha,Kola_nuts_Area_harvested_ha,Kola_nuts_Production_t,Kola_nuts_Yield_kg/ha,Leeks_and_other_alliaceous_vegetables_Area_harvested_ha,Leeks_and_other_alliaceous_vegetables_Production_t,Leeks_and_other_alliaceous_vegetables_Yield_kg/ha,Lemons_and_limes_Area_harvested_ha,Lemons_and_limes_Production_t,Lemons_and_limes_Yield_kg/ha,"Lentils,_dry_Area_harvested_ha","Lentils,_dry_Production_t","Lentils,_dry_Yield_kg/ha",Lettuce_and_chicory_Area_harvested_ha,Lettuce_and_chicory_Production_t,Lettuce_and_chicory_Yield_kg/ha,Linseed_Area_harvested_ha,Linseed_Production_t,Linseed_Yield_kg/ha,Locust_beans_(carobs)_Area_harvested_ha,Locust_beans_(carobs)_Production_t,Locust_beans_(carobs)_Yield_kg/ha,Lupins_Area_harvested_ha,Lupins_Production_t,Lupins_Yield_kg/ha,Maize_(corn)_Area_harvested_ha,Maize_(corn)_Production_t,Maize_(corn)_Yield_kg/ha,"Mangoes,_guavas_and_mangosteens_Area_harvested_ha","Mangoes,_guavas_and_mangosteens_Production_t","Mangoes,_guavas_and_mangosteens_Yield_kg/ha",Margarine_and_shortening_Production_t,Maté_leaves_Area_harvested_ha,Maté_leaves_Production_t,Maté_leaves_Yield_kg/ha,"Meat,_Poultry_Producing_Animals/Slaughtered_1000_An","Meat,_Poultry_Production_t","Meat,_Poultry_Yield/Carcass_Weight_g/An","Meat,_Total_Production_t","Meat,_Total_Stocks_1000_An","Meat_of_asses,_fresh_or_chilled_Producing_Animals/Slaughtered_An","Meat_of_asses,_fresh_or_chilled_Production_t","Meat_of_asses,_fresh_or_chilled_Yield/Carcass_Weight_kg/An","Meat_of_buffalo,_fresh_or_chilled_Producing_Animals/Slaughtered_An","Meat_of_buffalo,_fresh_or_chilled_Production_t","Meat_of_buffalo,_fresh_or_chilled_Yield/Carcass_Weight_kg/An","Meat_of_camels,_fresh_or_chilled_Producing_Animals/Slaughtered_An","Meat_of_camels,_fresh_or_chilled_Production_t","Meat_of_camels,_fresh_or_chilled_Yield/Carcass_Weight_kg/An","Meat_of_cattle_with_the_bone,_fresh_or_chilled_Producing_Animals/Slaughtered_An","Meat_of_cattle_with_the_bone,_fresh_or_chilled_Production_t","Meat_of_cattle_with_the_bone,_fresh_or_chilled_Yield/Carcass_Weight_kg/An","Meat_of_chickens,_fresh_or_chilled_Producing_Animals/Slaughtered_1000_An","Meat_of_chickens,_fresh_or_chilled_Production_t","Meat_of_chickens,_fresh_or_chilled_Yield/Carcass_Weight_g/An","Meat_of_ducks,_fresh_or_chilled_Producing_Animals/Slaughtered_1000_An","Meat_of_ducks,_fresh_or_chilled_Production_t","Meat_of_ducks,_fresh_or_chilled_Yield/Carcass_Weight_g/An","Meat_of_geese,_fresh_or_chilled_Producing_Animals/Slaughtered_1000_An","Meat_of_geese,_fresh_or_chilled_Production_t","Meat_of_geese,_fresh_or_chilled_Yield/Carcass_Weight_g/An","Meat_of_goat,_fresh_or_chilled_Producing_Animals/Slaughtered_An","Meat_of_goat,_fresh_or_chilled_Production_t","Meat_of_goat,_fresh_or_chilled_Yield/Carcass_Weight_kg/An","Meat_of_mules,_fresh_or_chilled_Producing_Animals/Slaughtered_An","Meat_of_mules,_fresh_or_chilled_Production_t","Meat_of_mules,_fresh_or_chilled_Yield/Carcass_Weight_kg/An","Meat_of_other_domestic_camelids,_fresh_or_chilled_Producing_Animals/Slaughtered_An","Meat_of_other_domestic_camelids,_fresh_or_chilled_Production_t","Meat_of_other_domestic_camelids,_fresh_or_chilled_Yield/Carcass_Weight_kg/An","Meat_of_other_domestic_rodents,_fresh_or_chilled_Producing_Animals/Slaughtered_1000_An","Meat_of_other_domestic_rodents,_fresh_or_chilled_Production_t","Meat_of_other_domestic_rodents,_fresh_or_chilled_Yield/Carcass_Weight_g/An","Meat_of_pig_with_the_bone,_fresh_or_chilled_Producing_Animals/Slaughtered_An","Meat_of_pig_with_the_bone,_fresh_or_chilled_Production_t","Meat_of_pig_with_the_bone,_fresh_or_chilled_Yield/Carcass_Weight_kg/An","Meat_of_pigeons_and_other_birds_n.e.c.,_fresh,_chilled_or_frozen_Producing_Animals/Slaughtered_1000_An","Meat_of_pigeons_and_other_birds_n.e.c.,_fresh,_chilled_or_frozen_Production_t","Meat_of_pigeons_and_other_birds_n.e.c.,_fresh,_chilled_or_frozen_Yield/Carcass_Weight_g/An","Meat_of_rabbits_and_hares,_fresh_or_chilled_Producing_Animals/Slaughtered_1000_An","Meat_of_rabbits_and_hares,_fresh_or_chilled_Production_t","Meat_of_rabbits_and_hares,_fresh_or_chilled_Yield/Carcass_Weight_g/An","Meat_of_sheep,_fresh_or_chilled_Producing_Animals/Slaughtered_An","Meat_of_sheep,_fresh_or_chilled_Production_t","Meat_of_sheep,_fresh_or_chilled_Yield/Carcass_Weight_kg/An","Meat_of_turkeys,_fresh_or_chilled_Producing_Animals/Slaughtered_1000_An","Meat_of_turkeys,_fresh_or_chilled_Production_t","Meat_of_turkeys,_fresh_or_chilled_Yield/Carcass_Weight_g/An",Melonseed_Area_harvested_ha,Melonseed_Production_t,Melonseed_Yield_kg/ha,"Milk,_Total_Milk_Animals_An","Milk,_Total_Production_t",Millet_Area_harvested_ha,Millet_Production_t,Millet_Yield_kg/ha,Mixed_grain_Area_harvested_ha,Mixed_grain_Production_t,Mixed_grain_Yield_kg/ha,Molasses_Production_t,Mules_and_hinnies_Stocks_An,Mushrooms_and_truffles_Production_t,Mustard_seed_Area_harvested_ha,Mustard_seed_Production_t,Mustard_seed_Yield_kg/ha,Natural_honey_Production_t,Natural_rubber_in_primary_forms_Area_harvested_ha,Natural_rubber_in_primary_forms_Production_t,Natural_rubber_in_primary_forms_Yield_kg/ha,"Nutmeg,_mace,_cardamoms,_raw_Area_harvested_ha","Nutmeg,_mace,_cardamoms,_raw_Production_t","Nutmeg,_mace,_cardamoms,_raw_Yield_kg/ha",Oats_Area_harvested_ha,Oats_Production_t,Oats_Yield_kg/ha,Oil_of_linseed_Production_t,Oil_of_maize_Production_t,Oil_of_palm_kernel_Production_t,Oil_of_sesame_seed_Production_t,Oil_palm_fruit_Area_harvested_ha,Oil_palm_fruit_Production_t,Oil_palm_fruit_Yield_kg/ha,"Oilcrops,_Cake_Equivalent_Area_harvested_ha","Oilcrops,_Cake_Equivalent_Production_t","Oilcrops,_Cake_Equivalent_Yield_kg/ha","Oilcrops,_Oil_Equivalent_Area_harvested_ha","Oilcrops,_Oil_Equivalent_Production_t","Oilcrops,_Oil_Equivalent_Yield_kg/ha",Okra_Area_harvested_ha,Okra_Production_t,Okra_Yield_kg/ha,Olive_oil_Production_t,Olives_Area_harvested_ha,Olives_Production_t,Olives_Yield_kg/ha,"Onions_and_shallots,_dry_(excluding_dehydrated)_Area_harvested_ha","Onions_and_shallots,_dry_(excluding_dehydrated)_Production_t","Onions_and_shallots,_dry_(excluding_dehydrated)_Yield_kg/ha","Onions_and_shallots,_green_Area_harvested_ha","Onions_and_shallots,_green_Production_t","Onions_and_shallots,_green_Yield_kg/ha",Oranges_Area_harvested_ha,Oranges_Production_t,Oranges_Yield_kg/ha,"Other_beans,_green_Area_harvested_ha","Other_beans,_green_Production_t","Other_beans,_green_Yield_kg/ha",Other_berries_and_fruits_of_the_genus_vaccinium_n.e.c._Area_harvested_ha,Other_berries_and_fruits_of_the_genus_vaccinium_n.e.c._Production_t,Other_berries_and_fruits_of_the_genus_vaccinium_n.e.c._Yield_kg/ha,Other_birds_Stocks_1000_An,Other_camelids_Stocks_An,"Other_citrus_fruit,_n.e.c._Area_harvested_ha","Other_citrus_fruit,_n.e.c._Production_t","Other_citrus_fruit,_n.e.c._Yield_kg/ha","Other_fibre_crops,_raw,_n.e.c._Area_harvested_ha","Other_fibre_crops,_raw,_n.e.c._Production_t","Other_fibre_crops,_raw,_n.e.c._Yield_kg/ha","Other_fruits,_n.e.c._Area_harvested_ha","Other_fruits,_n.e.c._Production_t","Other_fruits,_n.e.c._Yield_kg/ha","Other_meat_of_mammals,_fresh_or_chilled_Production_t","Other_nuts_(excluding_wild_edible_nuts_and_groundnuts),_in_shell,_n.e.c._Area_harvested_ha","Other_nuts_(excluding_wild_edible_nuts_and_groundnuts),_in_shell,_n.e.c._Production_t","Other_nuts_(excluding_wild_edible_nuts_and_groundnuts),_in_shell,_n.e.c._Yield_kg/ha","Other_oil_seeds,_n.e.c._Area_harvested_ha","Other_oil_seeds,_n.e.c._Production_t","Other_oil_seeds,_n.e.c._Yield_kg/ha",Other_pome_fruits_Area_harvested_ha,Other_pome_fruits_Production_t,Other_pome_fruits_Yield_kg/ha,Other_pulses_n.e.c._Area_harvested_ha,Other_pulses_n.e.c._Production_t,Other_pulses_n.e.c._Yield_kg/ha,Other_rodents_Stocks_1000_An,"Other_stimulant,_spice_and_aromatic_crops,_n.e.c._Area_harvested_ha","Other_stimulant,_spice_and_aromatic_crops,_n.e.c._Production_t","Other_stimulant,_spice_and_aromatic_crops,_n.e.c._Yield_kg/ha",Other_stone_fruits_Area_harvested_ha,Other_stone_fruits_Production_t,Other_stone_fruits_Yield_kg/ha,Other_sugar_crops_n.e.c._Area_harvested_ha,Other_sugar_crops_n.e.c._Production_t,Other_sugar_crops_n.e.c._Yield_kg/ha,"Other_tropical_fruits,_n.e.c._Area_harvested_ha","Other_tropical_fruits,_n.e.c._Production_t","Other_tropical_fruits,_n.e.c._Yield_kg/ha","Other_vegetables,_fresh_n.e.c._Area_harvested_ha","Other_vegetables,_fresh_n.e.c._Production_t","Other_vegetables,_fresh_n.e.c._Yield_kg/ha",Palm_kernels_Production_t,Palm_oil_Production_t,Papayas_Area_harvested_ha,Papayas_Production_t,Papayas_Yield_kg/ha,Peaches_and_nectarines_Area_harvested_ha,Peaches_and_nectarines_Production_t,Peaches_and_nectarines_Yield_kg/ha,Pears_Area_harvested_ha,Pears_Production_t,Pears_Yield_kg/ha,"Peas,_dry_Area_harvested_ha","Peas,_dry_Production_t","Peas,_dry_Yield_kg/ha","Peas,_green_Area_harvested_ha","Peas,_green_Production_t","Peas,_green_Yield_kg/ha","Pepper_(Piper_spp.),_raw_Area_harvested_ha","Pepper_(Piper_spp.),_raw_Production_t","Pepper_(Piper_spp.),_raw_Yield_kg/ha","Peppermint,_spearmint_Area_harvested_ha","Peppermint,_spearmint_Prod

In [134]:
FAO_Dataset_19_23.to_csv("../data/FAO_Dataset_19_23.csv")